INSERT INTO verse_text (verse_id, version_id, text) VALUES (29209, 17, 'Paulo - apóstolo do Cristo Jesus pela vontade de Deus - aos Santos, e fiéis em Cristo Jesus, que estão em Éfeso;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29210, 17, 'a vós, <b>saudações (graça)</b> e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29211, 17, 'Bendito o Deus e Pai do nosso Senhor Jesus Cristo,  o qual nos abençoou com toda benção espiritual nos (*lugares*) celestiais em Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29212, 17, 'assim como nos escolheu, nele, antes da fundação do mundo, para sermos santos e sem culpa, diante dele, no amor;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29213, 17, 'predestinando-nos para adoção (como filhos) junto a ele, mediante Jesus Cristo, segundo a benevolência da sua vontade;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29214, 17, 'para louvor da glória da sua <b>caridade (graça)</b>, com a qual nos agraciou, no Amado,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29215, 17, 'no qual temos a redenção - mediante o sangue dele -, e o perdão das transgressões, segundo a riqueza da sua <b>caridade (graça)</b> -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29216, 17, 'a qual nos deu abundantemente, em toda sabedoria e inteligência -,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29217, 17, 'dando-nos a conhecer o mistério da sua vontade, segundo a sua benevolência, a qual (*ele*) apresentou nele (Jesus)');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29218, 17, 'para administração da plenitude dos tempos, convergindo todas as coisas nele, em Cristo, tanto as dos céus como as da terra.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29219, 17, 'Nele, também fomos feitos herança, predestinados, segundo o propósito daquele que realiza todas as coisas, conforme a decisão da sua vontade;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29220, 17, 'a fim de sermos para louvor de sua glória, nós, que esperamos antecipadamente em Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29221, 17, 'em quem também vós, depois que ouvistes a palavra da verdade, o evangelho da vossa salvação, também tendo crido nele, fostes selados com o Espírito da promessa - o Santo -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29222, 17, 'aquele que é penhor da nossa herança, para redenção da (sua) aquisição, para louvor da sua glória.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29223, 17, 'Por isso, eu também, tendo ouvido (sobre) a fé no Senhor Jesus que (há) entre vós, e o amor para como todos os santos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29224, 17, 'não cesso de agradecer por vós, fazendo menção em minhas orações,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29225, 17, 'a fim de que o Deus do nosso Senhor Jesus Cristo, o Pai da Glória, vos dê espírito de sabedoria e revelação no conhecimento dele;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29226, 17, 'sendo iluminados os olhos do vosso coração, para saberdes qual é a esperança do chamamento dele, qual a riqueza da glória da herança dele, entre os santos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29227, 17, 'e qual a extraordinária grandeza do poder dele, para nós - os que cremos conforme a operação da força do seu poder.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29228, 17, 'A qual (força) ele exerceu em Cristo, ressuscitando-o dentre os mortos, e fazendo-o sentar-se à direita dele, nos (lugares) celestiais -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29229, 17, 'acima de todo principado e poder, domínio e senhorio, e de todo nome nomeado, não somente nesta era, mas também na vindoura.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29230, 17, 'E subordinou todas as coisas sob os pés dele, e (como) cabeça sobre todas as coisas o deu à igreja -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29231, 17, 'a qual é o corpo dele, a plenitude daquele que a tudo enche em todas coisas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29232, 17, 'E (*o deu*) a vós, estando (*vós*) mortos nas vossas transgressões e pecados,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29233, 17, 'nos quais andastes outrora, segundo a era (*o ciclo*) deste mundo, conforme o príncipe da autoridade do ar - o espírito que agora atua nos filhos da desobediência -;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29234, 17, 'entre os quais, outrora, nós todos também permanecíamos - nos desejos da nossa carne, realizando as vontades da carne e dos pensamentos - e éramos, por natureza, filhos da ira, como também os demais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29235, 17, 'Mas Deus, sendo rico em misericórdia, por causa do grande amor com que nos amou,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29236, 17, 'e, estando nós mortos em nossas transgressões, nos deu vida com o Cristo - por caridade (graça) sois salvos -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29237, 17, 'e nos ressuscitou com (*ele*), e nos fez sentar com (ele) nos lugares celestiais, em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29238, 17, 'para que mostrasse nas eras vindouras a extraordinária riqueza da sua caridade (graça), em bondade para conosco, em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29239, 17, 'Portanto, pela <b>caridade (graça)</b> sois salvos, mediante a fé; mas isto não é de vós, é dádiva de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29240, 17, 'não de obras, a fim de que ninguém se orgulhe.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29241, 17, 'Pois somos realização (*obra, resultado do trabalho*) dele, criados em Cristo Jesus para boas obras, as quais Deus de antemão preparou para que andássemos nelas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29242, 17, 'Por isso, lembrai-vos de que, outrora, vós - gentios na carne, chamados incircuncisão por aqueles que se intitulam circuncisão na carne, feita por mão (*humana*) -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29243, 17, 'que, naquele tempo, estáveis sem Cristo, excluídos da cidadania de Israel, e estrangeiros (com relação) às alianças da promessa, não tendo esperança, e sem Deus no mundo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29244, 17, 'agora, porém, em Cristo Jesus, vós - os que outrora estavam longe - fostes feitos próximos, no sangue de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29245, 17, 'Porque ele é a nossa paz, aquele que fez de ambos um só, derrubando  a parede divisória da cerca, a inimizade;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29246, 17, 'abolindo, na sua carne,  a lei dos <b>mandamentos em forma de preceitos,</b> a fim de que os dois criassem, nele, um só novo homem que faz a paz;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29247, 17, 'e com Deus reconciliasse ambos, em um só corpo, mediante a cruz, matando a inimizade nela (na carne).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29248, 17, 'E, vindo (ele), evangelizou a paz a vós, aqueles que (estão) longe, e paz aos que (estão) perto;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29249, 17, 'por que, por meio dele, ambos temos acesso ao Pai, em um só Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29250, 17, 'Assim, já não sois estrangeiros e peregrinos, mas sois concidadãos dos Santos, e membros da família de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29251, 17, 'edificados sobre os alicerces dos apóstolos e profetas, sendo ele mesmo - Cristo Jesus - a pedra angular;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29252, 17, 'na qual, todo o edifício, bem ajustado, cresce para o santuário santo, no Senhor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29253, 17, 'no qual também vós sois co-edificados para habitação de Deus, em Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29254, 17, 'Por causa disto, eu, Paulo - o prisioneiro de Cristo em favor de vós, os gentios,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29255, 17, 'se de fato ouvistes a administração da <b>caridade (graça)</b> de Deus, dada a mim para vós -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29256, 17, 'segundo uma revelação, me foi dado a conhecer o mistério, conforme escrevi há pouco, resumidamente,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29257, 17, 'em relação ao qual podeis, lendo, compreender o meu entendimento sobre o mistério de Cristo -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29258, 17, 'aquele (mistério) que em outras gerações não foi dado a conhecer ao filhos dos homens, como agora foi revelado aos seus santos apóstolos e profetas, em Espírito -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29259, 17, 'serem os gentios co-herdeiros e co-membros do corpo, e co-participantes da promessa em Cristo Jesus, por meio do Evangelho -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29260, 17, 'do qual (Evangelho) fui constituído ministro, conforme a dádiva da <b>caridade (graça)</b> de Deus, doada a mim segundo a realização do seu poder.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29261, 17, 'A mim, o menor de todos os santos, foi dada esta <b>caridade (graça)</b> de evangelizar aos gentios a insondável riqueza de Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29262, 17, 'e esclarecer qual a administração do mistério oculto, desde as eras, em Deus - que todas as coisas criou -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29263, 17, 'a fim de que, agora, seja dado a conhecer aos principados e aos poderes, nos lugares celestiais, por meio da igreja, a multifacetada sabedoria de Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29264, 17, 'segundo o plano das eras, que ele realizou em Cristo Jesus, o nosso Senhor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29265, 17, 'no qual temos a audácia e o acesso à confiança, mediante a fidelidade dele (Jesus).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29266, 17, 'Por isso, (vos) peço não desanimardes nas minhas aflições por vós, pois nisto está a vossa glória.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29267, 17, 'Por causa disto, dobro os meus joelhos diante do Pai,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29268, 17, 'de quem toma o nome toda a família, tanto no céu quanto sobre a terra,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29269, 17, 'a fim de que vos dê, segundo a riqueza da sua glória, serdes fortalecidos com poder, mediante o Espírito dele, (presente) no homem interior;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29270, 17, 'que Cristo habite em vossos corações, mediante a fé, (estando vós) arraigados e fundamentados no amor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29271, 17, 'para que sejais capazes de compreender, com todos os santos, qual a largura, comprimento, altura e profundidade -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29272, 17, 'conhecer o amor de Cristo, que excede o entendimento - a fim de que sejais preenchidos com  com toda a plenitude de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29273, 17, 'Ora, àquele que pode fazer, acima de todas as coisas, imensamente mais do que pedimos ou pensamos, segundo o poder que opera em nós;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29274, 17, 'a ele a glória, na igreja e em Cristo Jesus, por todas as gerações das eras das eras, amém.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29275, 17, 'Portanto, eu, o prisioneiro no Senhor, vos exorto a que andeis dignamente na vocação a que fostes chamados,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29276, 17, 'com toda humildade, mansidão e com paciência, tolerando uns aos outros com amor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29277, 17, 'esforçando-vos por manter a unidade do Espírito, com o vínculo da paz;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29278, 17, 'um só corpo, e um só Espírito, como também fostes chamados em uma só esperança na vossa vocação;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29279, 17, 'um só Senhor, uma só fé, um só batismo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29280, 17, 'um só Deus e Pai de todos, que está sobre todos, (atua) por meio de todos e (está) em todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29281, 17, 'E, a cada um de vós foi dada a <b>caridade</b> (graça) segundo a medida do dom de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29282, 17, 'Por isso diz: “Subindo ao alto, levou cativo um grupo de cativos; deu dons aos homens”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29283, 17, 'E o que é “subiu”? Senão que também desceu para as (regiões) inferiores da Terra?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29284, 17, 'Aquele que desceu é também o mesmo que subiu, acima de todos os céus, a fim de preencher todas as coisas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29285, 17, 'E ele mesmo concedeu uns para apóstolos, outros para profetas, outros evangelistas, outros pastores e Mestres;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29286, 17, 'para o aperfeiçoamento dos Santos com vistas à obra do ministério, para edificação do corpo de Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29287, 17, 'até que todos cheguemos à unidade da fé e do conhecimento do Filho de Deus, ao homem perfeito, à medida da estatura da plenitude de Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29288, 17, 'a fim de que não mais sejamos crianças, arrastados pelas ondas e levados por todo vento de doutrina, na artimanha dos homens, na astúcia para a maquinação do erro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29289, 17, 'Mas, seguindo a verdade em amor, cresçamos em todas as coisas para ele - aquele que é cabeça - o Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29290, 17, 'de quem todo corpo, bem ajustado e unido, pela provisão de cada junta, conforme a adequada operação de cada uma das partes, efetua o crescimento desse corpo, para a edificação de si mesmo em amor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29291, 17, 'Portanto, digo isto, e testemunho no Senhor: não mais andeis como os gentios também andam, na vaidade da mentalidade deles,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29292, 17, 'obscurecidos de entendimento, alienados da vida de Deus por causa da ignorância existente neles, em razão da dureza do coração deles;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29293, 17, 'os quais, tendo se tornado insensíveis, se entregaram à devassidão para prática, com avidez, de toda impureza');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29294, 17, 'Vós, porém, não aprendestes assim de Cristo -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29295, 17, 'se é que, de fato, ouvistes a ele, e fostes instruídos nele, conforme é a verdade em Jesus -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29296, 17, 'a vos despojardes do velho homem, segundo a conduta anterior, o qual se corrompe de conformidade com os desejos do engano,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29297, 17, 'e serdes renovados no espírito da vossa mentalidade,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29298, 17, 'para vos revestirdes do novo homem, criado segundo Deus em justiça e santidade da verdade.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29299, 17, 'Por isso, despojando-vos da mentira, falai a verdade, cada qual com o seu próximo, porque somos membros uns dos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29300, 17, 'Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29301, 17, 'nem deis lugar ao diabo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29302, 17, 'Aquele que rouba, não roube mais, mas antes se esforce, trabalhando  o bom com as próprias mãos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29303, 17, 'Nenhuma palavra corrompida sai da vossa boca, mas somente a que for boa para edificação da necessidade, a fim de que doe <b>caridade</b> (graça) aos que ouvem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29304, 17, 'E não entristeçais o Espírito Santo de Deus, no qual fostes selados para o dia da redenção.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29305, 17, 'Toda amargura, raiva, ira, gritaria e blasfêmia, como também toda maldade seja removida de vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29306, 17, 'Sede bondosos uns com os outros, compassivos, perdoando uns aos outros, como também Deus vos perdoou em Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29307, 17, 'Portanto, sede imitadores de Deus, como filhos amados,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29308, 17, 'e andai em amor, assim como Cristo nos amou e entregou a si mesmo, por nós, como oferta e sacrifício a Deus, em fragrância de agradável odor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29309, 17, 'Mas imoralidade e todo (tipo) de impureza ou avareza nem mesmo seja nomeada entre vós, como convém a santos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29310, 17, 'assim também obscenidade, conversa tola e conversa indecente, as quais não convém; mas antes <b>ação caridosa</b> (ação de graças).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29311, 17, 'Conhecendo, pois, isto: Sabeis que todo imoral ou impuro, ou avarento - que é idólatra - não possui herança no Reino de Cristo e de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29312, 17, 'Ninguém vos engane com palavras vazias; porque, por causa destas coisas, vem a ira de Deus sobre os “filhos da desobediência” (desobedientes).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29313, 17, 'Portanto, não vos torneis co-participantes deles;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29314, 17, 'Pois, outrora, éreis trevas, porém, agora, sois luz no Senhor; andai como “filhos da luz” -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29315, 17, 'pois o fruto da luz (consiste) em toda bondade, justiça e verdade -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29316, 17, 'discernindo o que é agradável ao Senhor;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29317, 17, 'e não co-participeis das obras infrutíferas das trevas; antes, porém, reprovai-as.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29318, 17, 'Porque as coisas feitas em segredo por eles, até dizer é vergonhoso.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29319, 17, 'No entanto, todas as coisas, quando reprovadas pela luz, se tornam manifestas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29320, 17, 'porque tudo que se torna manifesto é luz. Pelo que diz: “Acorda, o que dorme, e levanta-te dentre os mortos, e Cristo brilhará sobre ti”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29321, 17, 'Assim, vede cuidadosamente como andais, não como insensatos, mas como sensatos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29322, 17, 'resgatando (remindo) o tempo, porque os dias são maus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29323, 17, 'Por isso não sejais tolos, mas compreendei qual a vontade do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29324, 17, 'E não vos embriagueis com vinho, no qual há prodigalidade, mas estejais repletos no Espírito,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29325, 17, 'falando a vós mesmos com salmos, hinos e cânticos espirituais, cantando e louvando ao Senhor com o vosso coração,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29326, 17, 'agradecendo sempre por todas as coisas, em nome do nosso Senhor Jesus Cristo, ao Deus e Pai.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29327, 17, 'Subordinai-vos uns aos outros, no temor de Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29328, 17, 'as mulheres aos próprios homens, como ao Senhor;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29329, 17, 'porque o homem é cabeça da mulher, como também Cristo é cabeça da igreja, ele mesmo salvador do corpo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29330, 17, 'mas como a igreja está subordinada ao Cristo, assim também as mulheres aos homens, em tudo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29331, 17, 'Os homens, amai as mulheres, como também Cristo amou a igreja, e entregou a si mesmo por ela,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29332, 17, 'para que a ela santificasse, purificando-a no banha da água da palavra,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29333, 17, 'a fim de que ele apresentasse a igreja, a si mesmo, gloriosa, não possuindo mancha ou ruga, ou algo destas coisas, mas para que seja santa e sem defeito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29334, 17, 'Assim também, é necessário os homens amarem as suas próprias mulheres, como aos seus próprios corpos. Aquele que ama a sua própria mulher, a sim mesmo ama.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29335, 17, 'Pois ninguém jamais odiou a sua própria carne; ao contrário, alimenta e cuida dela, como também o Cristo a igreja -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29336, 17, 'porque somos membros do corpo dele -.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29337, 17, 'Por isso, deixará o homem ao Pai e à mãe e se unirá à sua mulher, e os dois serão uma só carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29338, 17, 'Grande é este mistério: eu falo, porém, a respeito do Cristo, e a respeito da igreja.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29339, 17, 'Entretanto, também vós, um a um, ame desse modo cada qual à sua própria mulher, como a si mesmo; e a mulher tema o homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29340, 17, 'Os filhos, obedecei aos vossos pais, no Senhor; pois isto é justo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29341, 17, '“Honra o teu pai e a tua mãe” - o qual é o primeiro mandamento na promessa -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29342, 17, '“a fim de que suceda a ti o bem, e sejas de longa vida sobre a terra”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29343, 17, 'E os pais, não provoqueis a ira dos vossos filhos, mas alimentai os mesmos na educação e admoestação do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29344, 17, 'Os escravos, obedecei aos senhores - segundo a carne - com temor e tremor, na simplicidade do vosso coração, como a Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29345, 17, 'não segundo um serviço aparente, como bajuladores de homens, mas como escravos de Cristo, fazendo de alma a vontade de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29346, 17, 'servindo com boa-vontade, como ao Senhor, e não a homens,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29347, 17, 'sabendo que cada um, se algo fizer de bom, isto receberá junto ao Senhor, quer seja escravo, quer seja livre.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29348, 17, 'E os Senhores, as mesmas coisas fazei para com eles, deixando a ameaça, sabendo que tanto o deles quanto o vosso Senhor está nos céus, e não há parcialidade junto a ele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29349, 17, 'Quanto ao mais, sede fortalecidos no Senhor, e na força do poder dele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29350, 17, 'Revesti-vos da armadura de Deus para poderdes ficar firmes contra as maquinações do diabo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29351, 17, 'porque não é para nós a luta contra sangue e carne, mas contra principados, contra os poderes, contra os dominadores da treva deste mundo, contra as (coisas) espirituais do mal nas (regiões) celestes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29352, 17, 'Por isso, tomai a armadura de Deus a fim de que possais resistir no dia mau e, tendo feito todas as coisas, permaneçam firmes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29353, 17, 'Portanto, permanecei firmes, cingindo a vossa cintura com a verdade, e vestindo a couraça da justiça,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29354, 17, 'calçando os pés com a preparação do Evangelho da Paz;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29355, 17, 'em todas as coisas, tomando o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29356, 17, 'tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29357, 17, 'mediante toda oração e súplica, orando em todo tempo no Espírito, e para isto vigiando com toda perseverança e súplica por todos os santos');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29358, 17, 'e também por mim; para que me seja dada a palavra, no abrir da minha boca, para tornar conhecido o mistério do Evangelho, com intrepidez,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29359, 17, 'do qual sou embaixador, em cadeias, a fim de que eu seja intrépido nele, conforme for necessário eu falar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29360, 17, 'E, para que saibais também a meu respeito e o que faço, Tíquico, o amado e fiel irmão, ministro no Senhor, vos fará saber todas as coisas,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29361, 17, 'o qual vos enviei para isto mesmo, para que conheçais as coisas a nosso respeito, e console os vossos corações.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29362, 17, 'Paz aos irmãos e amor com fé, da parte de Deus Pai e do Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29363, 17, '<b>Gratidão</b> (graça) a todos os que amam o nosso Senhor Jesus Cristo, de modo imperecível.');