INSERT INTO verse_text (verse_id, version_id, text) VALUES (29364, 17, 'Paulo e Timóteo, servos do Cristo Jesus, a todos os santos em Cristo Jesus - os que estão em Filipos - com supervisores (epíscopos) e servidores (diáconos);');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29365, 17, 'a vós, saudações (graça) e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29366, 17, 'Gratidão (graça) ao meu Deus, em cada lembrança de vós,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29367, 17, 'em cada rogativa minha por todos vós, sempre fazendo com alegria  a rogativa');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29368, 17, 'pela vossa comunhão no Evangelho, desde o primeiro dia até agora.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29369, 17, 'Estou realmente persuadido disto: Aquele que começou a boa obra em vós, a completará até o dia do Cristo Jesus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29370, 17, 'Dessa forma, é para mim justo pensar isto a respeito de todos vós: por eu vos trazer no coração, tanto nas minhas algemas, quanto na defesa e confirmação do Evangelho, todos vós sois meus co-participantes da caridade (graça).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29371, 17, 'Pois Deus é minha testemunha de como anseio por todos vós, nas entranhas do Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29372, 17, 'E oro assim: Que o vosso amor aumente ainda mais e mais, no conhecimento e em todo discernimento,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29373, 17, 'para experimentardes as coisas excelentes, a fim de que sejais puros e sem culpa, no dia de Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29374, 17, 'repletos do fruto da justiça, por meio de Jesus Cristo, para glória e louvor de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29375, 17, 'E quero que saibais irmãos que as coisas que me sucederam vieram para o maior progresso do Evangelho,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29376, 17, 'de modo que as minhas algemas, em Cristo, se tornaram conhecidas no Pretório inteiro, e por todos os demais;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29377, 17, 'e a maioria dos irmãos, persuadidos no Senhor pelas minhas algemas, ousam falar a palavra mais sem temor ainda.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29378, 17, 'Alguns, de fato, proclamam o Cristo até por inveja e rivalidade, mas outros por boa vontade;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29379, 17, 'uns por amor - sabendo que permaneço na defesa do Evangelho -,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29380, 17, 'outros por rivalidade, anunciam o Cristo, não de modo puro, pensando suscitar aflição em relação às minhas algemas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29381, 17, 'Porém, que importa? Uma vez que Cristo - por todo modo, por pretexto, ou por verdade - seja anunciado, nisto não só me alegro, como também me alegrarei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29382, 17, 'Porque sei que isto, mediante a vossa rogativa e a provisão do Espírito de Jesus Cristo, resultará na minha salvação;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29383, 17, 'segunda a minha intensa expectativa e esperança de que em nada serei envergonhado; ao contrário, com toda intrepidez, tanto agora como sempre, Cristo será engrandecido em meu corpo, seja mediante a vida, seja mediante a morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29384, 17, 'Porquanto, para mim, o viver é Cristo, e o morrer é lucro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29385, 17, 'Entretanto, se o viver na carne é para mim fruto da obra, não sei o que escolherei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29386, 17, 'Ora, estou pressionado pelos dois, de um lado tendo o desejo de partir e estar com o Cristo - que (é) incomparavelmente melhor -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29387, 17, 'de outro lado sendo necessário permanecer na carne, por vossa causa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29388, 17, 'E, convencido disto, sei que ficarei e continuarei com todos vós, para o vosso progresso, e alegria da fé;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29389, 17, 'a fim de que o orgulho por vós aumente em mim, em Cristo Jesus, mediante a minha presença, novamente, junto a vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29390, 17, 'Apenas, vivei dignamente do Evangelho de Cristo, a fim de que tanto indo e vos vendo, quanto estando ausente, ouça essas coisas a vosso respeito: que estais firmes em um só espírito, com uma só alma lutando juntos pela fé do Evangelho;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29391, 17, 'e não sendo intimidados em nada pelos adversários, a qual (fé do Evangelho) é para eles indício de perdição, para vós, porém, de salvação, e isto da parte de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29392, 17, 'porque a vós foi graciosamente concedido, pelo Cristo, não somente crer nele, mas também padecer por ele;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29393, 17, 'possuindo o mesmo combate, tal qual vistes em mim, e agora ouvis (existir) em mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29394, 17, 'Paulo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29395, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29396, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29397, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29398, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29399, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29400, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29401, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29402, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29403, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29404, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29405, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29406, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29407, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29408, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29409, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29410, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29411, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29412, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29413, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29414, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29415, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29416, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29417, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29418, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29419, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29420, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29421, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29422, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29423, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29424, 17, 'Paulo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29425, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29426, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29427, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29428, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29429, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29430, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29431, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29432, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29433, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29434, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29435, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29436, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29437, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29438, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29439, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29440, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29441, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29442, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29443, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29444, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29445, 17, 'Paulo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29446, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29447, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29448, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29449, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29450, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29451, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29452, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29453, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29454, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29455, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29456, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29457, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29458, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29459, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29460, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29461, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29462, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29463, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29464, 17, '');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29465, 17, '');