INSERT INTO verse_text (verse_id, version_id, text) VALUES (29060, 17, 'Paulo, apóstolo - não da parte dos homens, nem por intermédio de homem, mas por intermédio de Jesus Cristo e de Deus Pai, que o ressuscitou dentre os mortos -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29061, 17, 'e todos os irmãos que (estão) comigo, às igrejas da Galácia:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29062, 17, 'Saudações (Charis) a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29063, 17, 'que deu a si mesmo pelos nossos pecados, para que nos libertasse dessa era presente má, segundo a vontade de Deus, nosso Pai;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29064, 17, 'a quem a glória pelas eras das eras, amém.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29065, 17, 'Admira-me que vos transfiram tão depressa daquele que vos chamou na caridade (graça) de Cristo para outro Evangelho;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29066, 17, 'que não é outro, a não ser (para) alguns que vos agitam e querem distorcer o Evangelho de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29067, 17, 'No entanto, mesmo se nós ou um anjo do céu anunciasse (um Evangelho) paralelo ao que vos anunciamos, seja anátema!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29068, 17, 'Como dissemos anteriormente, e novamente dizemos agora: se alguém vos anunciar (um Evangelho) paralelo ao que recebestes, seja anátema!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29069, 17, 'Agora, porém, estou persuadindo homens ou a Deus? Ou busco agradar a homens? Se (eu) ainda estivesse agradando a homens, não seria servo de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29070, 17, 'Portanto, irmãos, vos dou a conhecer o Evangelho, anunciado por mim, que não é conforme homem;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29071, 17, 'porquanto, da parte de homem, eu não o recebi, nem fui ensinado, mas mediante revelação de Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29072, 17, 'Porque ouvistes (qual foi), outrora, a minha conduta no Judaísmo, com que excesso (eu) perseguia a igreja de Deus, e a devastava;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29073, 17, '(como) eu progredia no Judaísmo bem mais do que muitos contemporâneos da minha raça, sendo (também) muito mais zeloso das tradições de meus ancestrais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29074, 17, 'Quando, porém, houve por bem a Deus - aquele que me separou do ventre de minha mãe e (me) chamou pela sua caridade (graça) -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29075, 17, 'revelar o Filho dele em mim, a fim de que eu o anunciasse entre os gentios, de pronto, não consultei nem carne nem sangue;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29076, 17, 'nem subi a Jerusalém para os (já eram) apóstolos antes de mim, mas parti para a Arábia, e novamente retornei a Damasco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29077, 17, 'Então, depois de três anos, subi a Jerusalém para visitar Cefas, e permaneci junto dele por quinze dias;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29078, 17, 'e não vi outro dos apóstolos, senão Tiago, o irmão do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29079, 17, 'As coisas que vos escrevo, perante Deus, vede que não minto.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29080, 17, 'Então, fui para as regiões da Síria e da Cilícia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29081, 17, 'E, (com relação) às igrejas da Judéia, que (estão) em Cristo, (eu) era um desconhecido de rosto.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29082, 17, 'Ao contrário, somente estavam ouvindo: Aquele que, outrora, nos perseguia, agora anuncia a fé que, outrora, devastava.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29083, 17, 'E glorificavam a Deus por mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29084, 17, 'Então, depois de catorze anos, novamente subi a Jerusalém com Barnabé, levando junto também Tito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29085, 17, 'Subi - segundo revelação - e apresentei a eles, em particular aos notáveis, o Evangelho que proclamo entre os Gentios, (para que) de algum modo (eu) não corra ou tenha corrido em vão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29086, 17, 'Todavia, nem Tito, sendo Grego, fora compelido a ser circuncidado;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29087, 17, 'no entanto, por causa dos que foram introduzidos secretamente, falsos irmãos - os quais se infiltraram para espionar a nossa liberdade, que temos em Cristo Jesus, a fim de nos escravizar - (?);');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29088, 17, 'a esses nem por (uma) hora cedemos em submissão, a fim de que a verdade do Evangelho perdurasse para vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29089, 17, 'E, da parte dos que presumem ser algo - o que eram anteriormente nada importa para mim - Deus não aceita a aparência do homem - portanto, esses que presumiam (ser algo), nada me acrescentaram;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29090, 17, 'mas, pelo contrário, quando viram que o Evangelho da incircuncisão me fora confiado, como a Pedro o da circuncisão -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29091, 17, 'pois aquele que agiu e Pedro para o apostolado da circuncisão, também agiu em mim para os Gentios -,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29092, 17, 'e conhecendo a caridade (graça) que me foi doada, Tiago, Cefas e João - os que presumiam ser colunas - deram a mim e a Barnabé as (mãos) direitas da comunhão, a fim de que nós (fossemos) para os Gentios, e eles (fossem) para a circuncisão;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29093, 17, '(recomendando-nos) somente que nos lembrássemos dos pobres, o que também me esforcei por fazer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29094, 17, 'Porém, quando Cefas veio a Antioquia, (eu) me opus a ele face a face, porque era repreensível (passível de repreensão);');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29095, 17, 'porquanto, antes de chegarem alguns da parte de Tiago, (ele) comia com os Gentios, porém, quando chegaram, recuava e se separava (deles), temendo os da circuncisão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29096, 17, 'E os demais Judeus participaram com ele da hipocrisia, do mesmo modo que também Barnabé foi retirado deles (Gentios) pela hipocrisia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29097, 17, 'Todavia, quando vi que não andavam corretamente, conforme a verdade do Evangelho, (eu) disse a Cefas diante de todos: Se tu, sendo Judeu, vives como um Gentio, e não como um Judeu, como constranges os Gentios a judaizarem-se?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29098, 17, 'Nós, Judeus por natureza e não pecadores dentre os Gentios -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29099, 17, 'sabendo, contudo, que o homem não é justificado por obras da Lei, senão mediante a fé de Jesus Cristo -, nós também cremos em Jesus Cristo, a fim de que sejamos justificados pela fé de Cristo, e não por obras da Lei, porque pelas obras da Lei nenhuma carne será justificada.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29100, 17, 'No entanto, se buscando sermos justificados em Cristo, nós mesmos também fomos encontrados (como) pecadores, então Cristo é administrador do pecado? De modo nenhum!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29101, 17, 'Portanto, se as coisas que demoli, novamente as edifico, constituo a mim mesmo um transgressor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29102, 17, 'Porque eu, mediante a própria Lei, morri para a Lei, a fim de viver para Deus. Fui crucificado juntamente com o Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29103, 17, 'Eu não mais vivo, mas Cristo vive em mim;  o que vivo agora na carne, vivo na fé do Filho de Deus, que me amou e entregou a si mesmo por mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29104, 17, 'Não anulo a caridade (graça) de Deus; pois, se a justiça (vem) mediante a Lei, então Cristo morreu em vão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29105, 17, 'Ó Gálatas, insensatos! Quem vos enfeitiçou? (Vós) a quem, perante os olhos, Jesus Cristo (lhes) foi apresentado como crucificado?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29106, 17, 'Quero aprender de vós somente isto: recebestes o Espírito por obras da Lei ou pela escuta da fé?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29107, 17, 'Então, sois insensatos (a tal ponto) que, tendo começado no Espírito, estejais concluindo agora na carne?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29108, 17, 'Sofrestes tantas coisas em vão? Se, na verdade, (foram) em vão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29109, 17, 'Aquele, pois, que vos concede o Espírito, e opera “poderes” (dinamis) entre vós, (será) por obras da Lei ou por escuta da fé?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29110, 17, 'Consoante Abraão “creu em Deus, lhe foi atribuído para justiça”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29111, 17, 'Sabei, portanto, que os da fé é que são filhos de Abraão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29112, 17, 'E, prevendo a Escritura que Deus justifica os Gentios pela fé, anunciou previamente a Abraão: “Em ti serão abençoados todos os Gentios”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29113, 17, 'Assim, os da fé são abençoados junto com o crente Abraão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29114, 17, 'Portanto, todos os que são das obras da Lei estão sob maldição, pois está escrito: “Maldito todo aquele que não permanece em todas as coisas escritas no livro da Lei, para praticá-las.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29115, 17, 'E, é evidente que ninguém é justificado, junto a Deus, na Lei; porque “O Justo viverá a partir da fé”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29116, 17, 'A Lei, porém, não é proveniente da fé. No entanto, “aquele que faz estas coisas viverá nelas”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29117, 17, 'Cristo nos resgatou da maldição da Lei, tornando-se maldição por nós, porque está escrito: “Maldito todo aquele que é pendurado sobre o madeiro”,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29118, 17, 'a fim de que chegasse a benção de Abraão aos Gentios, em Cristo Jesus, para que recebêssemos a promessa do Espírito, mediante a fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29119, 17, 'Irmãos, falo como homem: Ainda que proveniente de homem, tendo sido ratificada uma aliança, ninguém a revoga ou suplementa (acrescenta, aumenta).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29120, 17, 'E, as promessas foram ditas a Abraão e à semente dele. Não diz “e às sementes”, como (se fosse) a respeito de muitas, mas como (sendo) a respeito de um só, “e à tua semente”, que é Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29121, 17, 'E digo isto: A Lei, que veio quatrocentos e trinta anos depois, não priva de autoridade uma aliança previamente confirmada, para anular a promessa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29122, 17, 'Portanto, se a herança provem da Lei, já não é proveniente da promessa; porém, Deus doou graciosamente à Abraão, mediante promessa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29123, 17, 'Por que, então, a Lei? Foi adicionada por causa das transgressões, até que viesse a semente, a quem foi feita a promessa, prescrita por anjos, na mão de um mediador.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29124, 17, 'O mediador, porém, não é de um, mas Deus é UM.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29125, 17, 'Assim, a Lei (é) contra as promessas? De modo nenhum! No entanto, se fosse dada uma Lei capaz de dar vida, verdadeiramente (então), a justiça seria proveniente da Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29126, 17, 'Todavia, a Escritura confinou todas as coisas sob o pecado, a fim de que a promessa, proveniente da fé de Jesus Cristo, fosse dada aos que creem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29127, 17, 'Antes de vir, porém, a fé, éramos mantidos sob a vigília da Lei, enclausurados, para a fé que iria ser revelada.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29128, 17, 'Assim, a Lei se tornou nosso pedagogo, (nos levando) a Cristo, a fim de que fossemos justificados pela fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29129, 17, 'Tendo chegado, porém, a fé, não mais estamos sob o pedagogo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29130, 17, 'Portanto, todos sois filhos de Deus, mediante a fé no Cristo Jesus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29131, 17, 'porquanto, todos quantos fostes batizados em Cristo, vos revestistes de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29132, 17, 'Não há Judeu, nem Grego; não há escravo nem livre; não há homem e mulher; pois todos vós sois UM em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29133, 17, 'E, se vós (sois) de Cristo, então sois semente de Abraão, herdeiros segundo a promessa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29134, 17, 'Digo, porém, que por quanto tempo o herdeiro for criança, em nada difere do escravo, (embora) sendo senhor de todas as coisas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29135, 17, 'mas está sob guardiões e administradores até o tempo fixado pelo pai.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29136, 17, 'Assim também nós; quando éramos crianças, estávamos escravizados sob os componentes elementares do mundo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29137, 17, 'Todavia, quando veio a plenitude do tempo, Deus enviou o seu Filho, vindo (à existência) de mulher, vindo (à existência) sob a Lei,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29138, 17, 'a fim de resgatar os (que estão) sob a Lei, para que recebêssemos a adoção como filhos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29139, 17, 'E, porque sois filhos, Deus enviou aos nossos corações o espírito do seu Filho, que clama: Abbá, Pai.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29140, 17, 'De sorte que já não és escravo, mas filho; e, se filho, também herdeiro, mediante Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29141, 17, 'Outrora, no entanto, não conhecendo a Deus, servistes aos que por natureza não são deuses;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29142, 17, 'Agora, porém, conhecendo a Deus, ou melhor, sendo conhecidos por Deus, como voltais novamente aos fracos e pobres componentes elementares, aos quais novamente quereis servir (como escravos), outra vez?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29143, 17, 'Guardais dias, meses, tempos e anos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29144, 17, 'Temo por vós; que de algum modo (eu) não tenha trabalhado em vão por vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29145, 17, 'Sede como eu, pois também sou como vós; irmãos, (eu) vos suplico.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29146, 17, 'Sabeis que, por conta de uma enfermidade da carne, (eu) vos evangelizei pela primeira vez,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29147, 17, 'e não desprezastes nem rejeitastes a vossa provação, no que concerne à minha carne, mas me recebestes como anjo de Deus, como Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29148, 17, 'Onde, portanto, a vossa bem-aventurança? Pois vos dou testemunho de que, se possível, teríeis me dados os vossos olhos, depois de (os) arrancar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29149, 17, 'Sendo assim, tornei-me vosso inimigo vos dizendo a verdade?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29150, 17, 'São zelosos por vós, (porém) não apropriadamente; mas desejam vos excluir, a fim de que sejais zelosos por eles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29151, 17, 'É bom ser sempre zeloso pelo bem, e não somente quando estou presente convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29152, 17, 'Meus filhos - pelos quais novamente sofro dores de parto, até que o Cristo seja formado em vós -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29153, 17, 'quisera eu estar presente agora convosco, e alterar a minha voz; porque estou perplexo a vosso respeito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29154, 17, 'Dizei-me - aqueles que querem estar sob a Lei - não ouvis a Lei?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29155, 17, 'Porquanto, está escrito que Abraão teve dois filhos, um da escrava e um da livre.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29156, 17, 'Todavia, o da escrava foi gerado segundo a carne, ao passo que o da livre mediante a promessa -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29157, 17, 'essas (coisas) são ditas alegoricamente - porque essas são as duas alianças; uma, de um lado, proveniente do Monte Sinai, gerando para a escravidão, a qual é Agar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29158, 17, 'Agar é o Monte Sinai, na Arábia, e corresponde à Jerusalém atual, pois serve (como escrava) com os filhos dela.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29159, 17, 'Mas a Jerusalém do alto é livre, a qual é nossa mãe;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29160, 17, 'pois está escrito: “Alegra-te estéril, a que não deu à luz; irrompe e grita, a que não teve dores de parto; porque são mais numerosos os filhos da abandonada que os da que tem marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29161, 17, 'Vós, porém, irmãos, sois filhos da promessa, como Isaque.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29162, 17, 'Todavia, assim como aquele que foi gerado segundo a carne, outrora perseguia aquele (que foi gerado) segundo o Espírito, assim também agora.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29163, 17, 'Mas que diz a Escritura? “Expulsa a escrava, e o filho dela; pois o filho da escrava não herdará com o filho da livre”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29164, 17, 'Portanto, irmãos, não somos filhos da escrava, mas da livre.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29165, 17, 'Para a liberdade, Cristo nos libertou. Portanto, permanecei firmes, e não vos submetais, novamente, a jugo de escravidão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29166, 17, 'Vede! Eu, Paulo, vos digo que, se fordes circuncidados, Cristo de nada vos aproveitará.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29167, 17, 'E, novamente, dou testemunho a todo homem circuncidado de que (ele) está obrigado a praticar toda a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29168, 17, 'Fostes apartados de Cristo - (vós) que sois justificados na Lei -, da caridade (graça) decaístes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29169, 17, 'Porquanto, nós, pelo espírito, aguardamos a esperança da justiça, proveniente da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29170, 17, 'Pois, em Cristo Jesus, nem a circuncisão, nem a incircuncisão podem algo, mas (somente) a fé que opera por meio do amor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29171, 17, 'Corríeis bem. Quem vos obstruiu (para) não obedecerdes à verdade?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29172, 17, 'A persuasão não provem daquele que vos chama.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29173, 17, 'Pouco fermento fermenta a massa toda.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29174, 17, 'Estou persuadido a vosso respeito, no Senhor, que nada cogitareis de diferente (disso); mas aquele que está vos perturbando suportará o juízo, seja quem for.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29175, 17, 'Eu, porém, irmãos, se ainda estou proclamando a circuncisão, por que ainda sou perseguido? Nesse caso, então, está anulado o escândalo da cruz.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29176, 17, 'Bom seria que (eles) se castrassem - esses que vos perturbam.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29177, 17, 'Porque vós, irmãos, fostes chamados para a liberdade; somente não se torne a liberdade em uma oportunidade para a carne; ao contrário, servi (como escravos, servos) uns aos outros por meio do amor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29178, 17, 'Pois, toda a Lei é cumprida em uma palavra, nesta: “Amarás o teu próximo como a ti mesmo”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29179, 17, 'No entanto, se mordeis e devorais uns aos outros, vede que não sejais destruídos uns pelos outros!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29180, 17, 'Digo, porém: Andai no Espírito, e jamais “levareis a cabo” o desejo da carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29181, 17, 'Pois, a carne deseja contra o Espírito, e o Espírito contra a carne; portanto, essas coisas se opõem umas às outras, a fim de não fazerdes as coisas que desejais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29182, 17, 'Mas, se sois guiados pelo Espírito, não estais sob a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29183, 17, 'Evidentes são as obras da carne, quais sejam: prostituição (porneia, relações sexuais ilícitas, imoralidade sexual), impureza (física, ritual e moral), devassidão (“aselgeia” - lascívia, libertinagem, perda do respeito ao outro e à opinião pública),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29184, 17, 'idolatria, drogadição (farmakeia, abuso de drogas, magia, poções mágicas, bruxaria), inimizades (individual, familiar, comunitária, étnica, religiosa, cultural), contenda (conflito, luta, disputa, rixas), ciúme (palavra com duplo sentido: zelo e ciúme), cóleras (impulso violento sem raciocínio, ira furiosa, crises de fúria), discórdias (desavenças, partidarismo), dissensões (separação, divisão, “ficar à parte, separado”, rivalidade individual, política e partidária), facções (grupos divididos e rivais),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29185, 17, 'invejas (dor diante da prosperidade e sucesso do outro, gerando atos concretos), bebedeiras e orgias, e coisas semelhantes a estas; as quais vos digo antecipadamente - como disse anteriormente - que aqueles que praticam tais coisas não herdarão o Reino de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29186, 17, 'O fruto do Espírito, porém, é: amor, alegria, paz, longanimidade (grandeza de ânimo em relação a pessoas e eventos, magnanimidade, indulgência),  benevolência (benignidade), bondade (expressa em ações concretas, generosidade), confiança (fé no sentido de fidelidade, entrega, confiança),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29187, 17, 'mansuetude, auto-domínio; contra tais coisas não existe Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29188, 17, 'E os que são de Cristo crucificaram a carne, com as paixões e os desejos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29189, 17, 'Se vivemos no Espírito, andemos também no Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29190, 17, 'Não nos tornemos presunçosos, provocando uns aos outros, tendo inveja uns dos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29191, 17, 'Irmãos, se um homem for flagrado em alguma transgressão, vós - os espirituais - restaurai tal (pessoa) com espírito de mansuetude, vigiando a ti mesmo para que tu também não sejas tentado');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29192, 17, 'Levai as cargas uns dos outros e, assim, cumprireis a Lei de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29193, 17, 'Porquanto, se alguém considera ser algo, nada sendo, engana a si mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29194, 17, 'Mas, examine cada qual sua própria obra e, então, somente para si mesmo terá orgulho, e não para outro;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29195, 17, 'pois, cada qual levará o próprio fardo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29196, 17, 'E o que é instruído na palavra comungue com aquele que o instrui, em todas as coisas boas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29197, 17, 'Não vos enganeis, Deus não é escarnecido (tratado com desprezo). Portanto, o que um homem semear, isso também colherá;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29198, 17, 'porque aquele que semeia para a carne, colherá corrupção proveniente da sua própria carne, mas aquele que semeia para o Espírito colherá vida eterna do Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29199, 17, 'E, fazendo o bem, não nos cansemos, pois no tempo apropriado colheremos (se) não desfalecermos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29200, 17, 'Assim, portanto, enquanto temos tempo, façamos o bem a todos, mas principalmente aos da família da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29201, 17, 'Vede com que grandes letras (eu) vos escrevi, com a minha mão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29202, 17, 'Todos aqueles que querem exibir uma boa aparência na carne vos constrangem a serdes circuncidados, somente para que não sejam perseguidos com relação à cruz de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29203, 17, 'Assim, nem eles mesmos - os que são circuncidados - guardam a Lei, mas querem que vós sejais circuncidados para que se orgulhem na vossa carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29204, 17, 'Quanto a mim, porém, não aconteça de (eu) me orgulhar, exceto na cruz do nosso Senhor Jesus Cristo, mediante quem o mundo está crucificado para mim, e eu para o mundo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29205, 17, 'Pois nem a circuncisão é algo, nem a incircuncisão, mas (ser) nova criação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29206, 17, 'E, a todos que estiverem conforme essa regra, paz e misericórdia (seja) sobre eles, e sobre o Israel de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29207, 17, 'Quanto ao mais, ninguém me cause fadiga (labor, aborrecimento decorrente de trabalho árduo), pois carrego em meu corpo as marcas de Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (29208, 17, 'A caridade (graça) do nosso Senhor Jesus Cristo (esteja) com o vosso espírito, irmãos; Amém.');