INSERT INTO verse_text (verse_id, version_id, text) VALUES (28367, 17, 'Paulo, chamado pela vontade de Deus (para ser) apóstolo de Cristo Jesus, e o irmão Sóstenes,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28368, 17, 'à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados Santos, com todos os que invocam, em todo lugar, o nome de Nosso Senhor Jesus Cristo, (Senhor) deles e nosso;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28369, 17, 'gratidão a vós e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28370, 17, 'Sou grato ao meu Deus, a vosso respeito, por causa da <b>caridade</b> (graça) de Deus, que vos foi doada em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28371, 17, 'Porque, em tudo, fostes enriquecidos nele, em toda a palavra e em todo o conhecimento.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28372, 17, 'Do mesmo modo, o testemunho de Cristo se confirma em vós,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28373, 17, 'de modo a não carecerdes de nenhum <b>dom</b> (dádiva, doação da caridade), esperando ansiosamente a revelação de Nosso Senhor Jesus Cristo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28374, 17, 'o qual também vos confirmará (como) irrepreensíveis, até ao fim (finalidade), no dia do Nosso Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28375, 17, 'Fiel (pistós) é Deus, por meio do qual fostes chamados para a comunhão com seu Filho, Jesus Cristo, Nosso Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28376, 17, 'Rogo-vos, irmãos, em nome do Nosso Senhor Jesus Cristo, para que todos faleis a mesma coisa, e não haja entre vós divisões, mas que estejais ajustados na mesma mente, e no mesmo parecer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28377, 17, 'Porquanto, meus irmãos, foi evidenciado pelos (da casa) de Cloé, que há disputas entre vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28378, 17, 'E digo isto, porque cada um de vós têm dito: “Eu sou de Paulo; eu sou de Apolo; eu sou de Cefas; eu sou de Cristo”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28379, 17, 'Porventura, o Cristo está dividido? Acaso, Paulo foi crucificado por vós? Ou fostes batizados em nome de Paulo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28380, 17, 'Sou grato (a Deus) porque a nenhum de vós batizei, exceto Crispo e Gaio,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28381, 17, 'a fim de que alguém não diga que fostes batizados em meu nome -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28382, 17, 'batizei também aos da casa de Estéfanas, de resto não sei se batizei algum outro -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28383, 17, 'Sendo assim, Cristo não me enviou para batizar, mas para evangelizar, não em sabedoria de palavras, para que a cruz de Cristo não seja <b>esvaziada</b> (perder valor, tornar-se vã).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28384, 17, 'Porquanto, a palavra da cruz é loucura para os que são destruídos (perecem), por outro lado é pode de Deus para nós, que somos salvos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28385, 17, 'Pois está escrito: “Destruirei a sabedoria dos sábios, e tornarei inválida a sagacidade dos sagazes”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28386, 17, 'Onde (está) o sábio? Onde (está) o escriba? Onde (está) o debatedor desta era? Porventura, Deus não tornou louca a sabedoria do mundo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28387, 17, 'Assim, visto que o mundo não conheceu a Deus através da sabedoria, o (próprio) Deus - na sabedoria de Deus - houve por bem salvar os que crêem, através da loucura da proclamação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28388, 17, 'Considerando que, tanto pedem sinais (os) Judeus, quanto buscam sabedoria os Gregos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28389, 17, 'nós, todavia, proclamamos Cristo crucificado - que (é) escândalo para Judeus, e loucura para Gregos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28390, 17, 'No entanto, para aqueles que foram chamados, tanto Judeus quanto Gregos, (proclamamos) Cristo, poder de Deus e sabedoria de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28391, 17, 'Porque a loucura de Deus é mais sábia do que os homens; e a fraqueza de Deus é mais forte do que os homens');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28392, 17, 'Considerai, portanto, o vosso chamado, irmãos, porque não (foram chamados) muitos sábios segundo a carne, nem muitos poderosos, nem muitos nobres.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28393, 17, 'Todavia, Deus escolheu as coisas loucas do mundo para envergonhar os sábios; e Deus escolheu as coisas fracas do mundo para envergonhar as coisas fortes;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28394, 17, 'e Deus escolheu as coisas insignificantes do mundo, e as coisas desprezadas, e aquelas que não têm existência para abolir aquelas que têm existência;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28395, 17, 'para que nenhuma carne se orgulhasse diante de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28396, 17, 'Mas vós sois dele (de Deus), em Cristo Jesus, o qual se tornou para nós sabedoria, que (vem) de Deus, justiça, santificação e redenção;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28397, 17, 'a fim de que - como está escrito - : “Aquele que se gloria, glorie-se no Senhor”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28398, 17, 'Eu, quando me dirigi a vós, anunciando-vos o mistério de Deus, cheguei não com excelência de palavra ou de sabedoria.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28399, 17, 'Porque não decidi, entre vós, saber algo, exceto, (o que concerne a) Jesus Cristo - o Crucificado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28400, 17, 'E eu fui até vós, em fraqueza, em temor e em grande tremor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28401, 17, 'A minha palavra e a minha proclamação (não consistiram) em (palavra) de sabedoria persuasiva, mas em demonstração de espírito e de poder,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28402, 17, 'a fim de que a vossa fé não estivesse (fundada) em sabedoria de homens, mas no poder de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28403, 17, 'Entretanto, expomos (falamos) sabedoria entre os maduros, porém, não a sabedoria desta era, nem dos líderes desta era, que estão desaparecendo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28404, 17, 'Expomos (falamos), porém, a sabedoria de Deus, tornada oculta no mistério - que Deus preordenou antes das eras - para nossa glória,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28405, 17, 'a qual (glória) nenhum dos líderes desta era conheceu, porque se tivessem conhecido não teriam crucificado o Senhor da glória;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28406, 17, 'mas, como está escrito: “O olho não vê, e os ouvidos não ouvem, nem alcança o coração do homem essas (coisas) que Deus prepara para aqueles que o amam”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28407, 17, 'Todavia, Deus nos revelou através do Espírito, porque o Espírito        perscruta todas as coisas, inclusive as coisas profundas de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28408, 17, 'Porquanto, qual dos homens conhece as coisas do homem, senão o espírito do homem que (está) nele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28409, 17, 'Nós, porém, recebemos não o espírito do mundo mas o Espírito (que vem) de Deus, que nos é <b>doado caridosamente</b> (graciosamente).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28410, 17, 'E dessas coisas falamos, não com palavras de sabedoria, (presentes) em ensinamentos de homem, mas interpretamos por comparação, nos ensinamentos do Espírito, (realidades) espirituais (em termos) espirituais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28411, 17, 'O homem <b>anímico</b>, porém, não aceita as coisas do Espírito de Deus, porquanto são loucura para ele, e não as pode entender, porque são examinadas espiritualmente.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28412, 17, 'Aquele que é espiritual, porém, examina todas coisas, ele mesmo, no entanto, por ninguém é examinado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28413, 17, '“Pois quem conhece a mente do Senhor, quem lhe aconselhará?” Nós, porém, temos a mente do Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28414, 17, 'Eu, irmãos, não pude vos falar como (a) espirituais, mas como (a) carnais, como (a) crianças em Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28415, 17, 'Leite vos dei de beber, não comida, porquanto não eram capazes. Por outro lado, nem agora ainda sois capazes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28416, 17, 'Porque ainda sois carnais. Porquanto, onde (há) inveja e discórdia entre vós, não (seria porque) sois carnais e andais segundo (o) homem?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28417, 17, 'Quando, pois, alguém disser: “Eu sou de Paulo”; e outro: “Eu (sou) de Apolo”; não sois (meramente) homens?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28418, 17, 'Portanto, o que é Apolo? O que é Paulo? Servos; mediante os quais crestes, (isto) conforme o Senhor concedeu a cada um.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28419, 17, 'Eu plantei, Apolo regou, mas Deus fez crescer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28420, 17, 'Por conseguinte, nem o que planta é alguma coisa, nem o que rega, mas (somente) aquele que faz crescer - Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28421, 17, 'Ora, o que planta e o que rega são um (iguais); e cada qual receberá o próprio pagamento, segundo a própria labuta.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28422, 17, 'Porque somos cooperadores de Deus, seara de Deus; edificação de Deus sois (vós).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28423, 17, 'Segundo a <b>caridade</b> (graça) de Deus, a mim doada, como sábio arquiteto assentei o alicerce; outro, porém, edifica por cima. Mas cada um observe como edifica por cima.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28424, 17, 'Porquanto, nenhum outro pode assentar alicerce além daquele que foi assentado, o qual é Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28425, 17, 'Contudo, se alguém edifica sobre o alicerce: ouro, prata, pedras preciosas, madeiras, feno, palha;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28426, 17, 'a obra de cada um se tornará manifesta, pois o Dia a tornará visível, porque é revelada no fogo; e o fogo provará de que espécie é a obra de cada um.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28427, 17, 'Se a obra de alguém permanecer - a que (ele) edificou por cima - receberá pagamento.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28428, 17, 'Se a obra de alguém for queimada, sofrerá dano; ele, porém, será salvo. Todavia, como que por meio de fogo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28429, 17, 'Não sabeis que sois Templo de Deus, e (que) o Espírito de Deus habita em vós?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28430, 17, 'Se alguém destrói o Templo de Deus, Deus a ele destrói, pois o Templo de Deus é santo - os quais (templos) sois vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28431, 17, 'Ninguém iluda a si mesmo: se alguém, dentre vós, considera ser sábio nesta era, torne-se louco, a fim que se torne sábio.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28432, 17, 'Porquanto a sabedoria deste mundo é loucura junto a Deus, pois está escrito: “Aquele que apanha os sábios na astúcia deles”;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28433, 17, 'e novamente: “O Senhor conhece os pensamentos dos sábios, que são vãos”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28434, 17, 'Por conseguinte, ninguém se glorie em homens, pois todas (as coisas) são vossas:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28435, 17, 'seja Paulo, seja Apolo, seja Cefas, seja o mundo, seja (a) vida, seja (a ) morte, sejam (as coisas) presentes, sejam (as) vindouras, tudo é vosso;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28436, 17, 'e vós, de Cristo; e Cristo, de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28437, 17, 'Assim, que (o) homem nos considere servos de Cristo, e administradores dos mistérios de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28438, 17, 'Além disso, nesse particular, o que se busca nos administradores (é) que  (esse) alguém seja encontrado fiel.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28439, 17, 'Todavia, é insignificante para mim que (eu) seja por vós julgado, ou por “dia humano” (tribunal humano, um dia do juízo mas humano); nem eu tampouco julgo a mim mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28440, 17, 'Porquanto, estou cônscio de nada (haver) contra mim, mas nem por isso estou justificado, pois aquele que me julga é (o) Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28441, 17, 'Por conseguinte, não julgueis algo antes da época (oportuna) - até que venha o Senhor - o qual também iluminará as coisas ocultas da treva, e manifestará os propósitos dos corações; e, então, o louvor, da parte de Deus, acontecerá para cada um.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28442, 17, 'Essas coisas, irmãos, apliquei a mim mesmo e a Apolo, por causa de vós, a fim de que, em nós, aprendais o “Não além das coisas que estão escritas”; para que não “fiqueis inchados” (fiqueis orgulhosos) a favor de um, (mas) em detrimento de outro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28443, 17, 'Pois quem te considera superior (aos demais)? E o que possuís que não tenhas recebido? E se também recebestes, por que te vanglorias como (alguém) que não tenha recebido?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28444, 17, 'Já estais saciados? Já estais ricos? Reinastes sem nós? Quisera, de fato, tivésseis reinado, a fim de que nós também reinássemos junto convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28445, 17, 'Considero, porém, que Deus exibiu a nós - os apóstolos - (como os) últimos, como condenados à morte, porque fomos feitos <b>teatro</b> (peça grega) ao mundo, aos anjos e aos homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28446, 17, 'Nós, por causa do Cristo, (somos) loucos; vós, porém, sábios em Cristo; nós (somos) fracos, vós, porém, fortes; vós (sois) honrados, nós, porém, desonrados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28447, 17, 'Até a presente hora, também temos fome, temos sede, vestimos trapos, somos esbofeteados, não temos morada (certa),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28448, 17, 'labutamos, trabalhando com as próprias mãos; ultrajados, bendizemos; perseguidos, suportamos;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28449, 17, 'difamados, consolamos; até agora, nos tornamos semelhantes à <b>catarse</b> (expiação, purificação, limpeza) do mundo, <b>limpeza</b> (limpar esfregando) de todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28450, 17, 'Não vos escrevo essas coisas para vos envergonhar, mas para vos admoestar como (a) filhos meu, amados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28451, 17, 'Porquanto, se dez mil pedagogos tivésseis, em Cristo, não (teríeis), porém, muitos pais. Porque, através do evangelho, eu vos gerei em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28452, 17, 'Portanto, vos exorto: Tornai-vos meus imitadores.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28453, 17, 'Por esta razão, vos enviei Timóteo, que é meu filho amado, fiel no Senhor; o qual vos fará lembrar os meus caminhos em Cristo, conforme (eu) ensino em toda parte, em cada igreja.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28454, 17, 'Alguns, porém, “<b>incharam-se”</b> (ensoberbeceram-se), como se eu não fosse mais até vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28455, 17, 'No entanto, em breve, irei até vós, se o Senhor quiser; e conhecerei não a palavra dos que “<b>se incharam</b>” (ensoberbeceram-se), mas o poder.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28456, 17, 'Porquanto, o Reino de Deus não (consiste) em palavra, mas em poder.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28457, 17, 'Que quereis? Que eu vá até vós com vara, ou com amor e espírito de mansidão?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28458, 17, 'De fato, ouve-se que (há) fornicações (relações sexuais ilícitas) entre vós, e fornicações (relações sexuais ilícitas) tal, que nem (mesmo) entre os gentios (existe), a ponto de alguém possuir a esposa do (próprio) pai.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28459, 17, 'E vós “<b>estais inchados</b>” (ensoberbecidos), e, ainda mais, nem sequer lamentastes, a fim de que fosse removida do vosso meio essa obra praticada.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28460, 17, 'Eu, porém, ausente no corpo, mas por outro lado presente no espírito, já sentenciei (julgar) - como (quem está) presente - aquele que praticou isso, dessa maneira;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28461, 17, 'em nome do Senhor Jesus, reunidos vós e o meu espírito, com o poder do Nosso Senhor Jesus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28462, 17, 'a entregar o tal a Satanás para destruição da carne, a fim de que o espírito seja salvo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28463, 17, 'Não é bom o vosso orgulho. Não sabeis que um pouco de fermento fermenta toda a massa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28464, 17, 'Lançai fora o velho fermento, a fim de que - como sois ázimo - sejais nova massa, pois também a nossa Páscoa - Cristo - foi imolada.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28465, 17, 'Sendo assim, celebremos a festa (Páscoa), não com fermento velho, nem com fermento de malícia e perversidade, mas como ázimos de sinceridade e <b>verdade</b> (oposto de erro e falsidade).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28466, 17, '(Eu) vos escrevi, na carta (anterior), para não vos associardes aos prostitutos -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28467, 17, 'não a todos os prostitutos deste mundo, aos avarentos, aos vorazes (para roubar), aos idólatras - pois então seria necessário sair do mundo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28468, 17, 'Agora, porém, vos escrevi para não vos associardes a alguém que, embora seja chamado de irmão, for prostituto, avarento, idólatra, difamador, beberrão, ou voraz (para roubar); com esse tal (não deveis) nem comer juntos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28469, 17, 'Acaso (compete) a mim julgar os de fora? Vós não julgais os de dentro?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28470, 17, 'No entanto, Deus julgará os de fora. Removei a perversidade do meio de vós mesmos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28471, 17, 'Ousa alguém dentre vós, tendo uma questão (litígio) contra o outro, ser julgado perante os injustos, e não perante os Santos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28472, 17, 'Ou não sabeis que os Santos julgarão o mundo? E, se o mundo é julgado por vós, sois indignos de cortes (de justiça) para (litígios) menores (em relevância)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28473, 17, 'Não sabeis que julgaremos os anjos? Quanto mais as coisas da vida (cotidiana).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28474, 17, 'Portanto, se tendes cortes (de justiça) para coisas da vida (cotidiana), convocas (a tomar assento na corte) a estes - os desprezados na igreja.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28475, 17, 'Falo para vossa vergonha. Não há, desse modo, nenhum sábio entre vós, o qual poderá julgar com discernimento (litígio) entre irmão dele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28476, 17, 'Todavia, é julgado (litígio) de irmão contra irmão, mas isso (é feito) pelos infiéis (descrentes)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28477, 17, 'O fato de que tendes demandas (processos judiciais) uns contra os outros ja é, por si mesmo, uma completa derrota para vós. Por que não sofreis, antes, a injustiça? Por que não sofreis, antes, o dano (a defraudação)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28478, 17, 'Ao contrário, vós fazeis injustiça, defraudais, e isto a irmãos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28479, 17, 'Ou não sabeis que os injustos não herdarão o Reino de Deus? Não vos enganeis: nem prostitutos, nem idólatras, nem adúlteros, nem “moles" (referência aos homens que se vestiam de mulher no culto a Cibele oferecendo-se para prática sexual ritual), nem depravados sexuais (estupradores, praticantes de orgia, estupradores),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28480, 17, 'nem ladrões, nem gananciosos, ou bêbados, ou difamadores, nem voraz (para roubar), herdarão o Reino de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28481, 17, 'Entretanto, alguns (de vós) (já) foram estas coisas. Porém, fostes lavados, fostes santificados, fostes justificados, em nome do Senhor Jesus Cristo, e no Espírito de nosso Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28482, 17, 'Todas as coisas me são lícitas, mas nem todas as coisas são proveitosas. Todas as coisas me são lícitas, mas não serei dominado por nenhuma.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28483, 17, 'Os alimentos são para o estômago, e o estômago para os alimentos, mas Deus inutilizará tanto estes (alimentos), quanto aquele (estômago). O corpo, porém, não (é) para fornicações (relações sexuais ilícitas), mas para o Senhor;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28484, 17, 'E Deus ergueu (ressuscitou) tanto ao Senhor, quanto nos erguerá (ressuscitará) pelo poder dele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28485, 17, 'Não sabeis que os vossos corpos são membros de Cristo? Tomarei, portanto, os membros de Cristo e farei (deles) membros de prostituta? De modo nenhum\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28486, 17, 'Não sabeis que aquele que está unido à prostituta é um só corpo (com ela)? Pois afirma (a Escritura): “Serão os dois uma só carne”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28487, 17, 'Porém, aquele que está unido ao Senhor é um só Espírito (com ele).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28488, 17, 'Fugi das fornicações (relações sexuais ilícitas). Todo pecado que um homem cometer está fora do corpo, mas o que pratica fornicações (relações sexuais ilícitas) peca contra o próprio corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28489, 17, 'Ou não sabeis que o vosso corpo é Templo do Espírito Santo que está em vós, o qual tendes da parte de Deus, e que não sois de vós mesmos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28490, 17, 'Assim, fostes comprados por valor, portanto, glorificai a Deus, em vosso corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28491, 17, 'A respeito das coisas que escrevestes, (é) bom para o homem não se ligar (se atracar - metáfora para ligações sexuais) a mulher.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28492, 17, 'Por causa das fornicações (relações sexuais ilícitas), cada um tenha a sua própria esposa, e cada uma tenha o seu próprio marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28493, 17, 'Cumpra (pague, entregue) o marido a obrigação (débito, dívida) para (com) a esposa, e também, de modo semelhante, a esposa para (com) o marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28494, 17, 'A esposa não exerce autoridade sobre o próprio corpo, mas o marido; assim também o marido não exerce autoridade sobre o próprio corpo, mas a esposa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28495, 17, 'Não priveis um ao outro (da relação sexual), senão de mútuo acordo, por um período (tempo determinado), para que tenhais um tempo livre para a oração;  e estejais novamente juntos, a fim de que Satanás não vos tente, por causa da vossa falta de auto-controle.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28496, 17, 'E digo isto por concessão (permissão, tolerância), não por ordem (imposição, comando)');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28497, 17, 'Quero que todos os homens sejam também como eu mesmo, mas cada qual possui seu próprio <b>dom</b> (dádiva, doação da caridade) de Deus; um, desse modo; outro, daquele modo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28498, 17, 'Digo aos não casados e às viúvas: bom seria para eles permanecerem também como eu.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28499, 17, 'Todavia, se não possuem auto-controle, que se casem; pois é melhor casar do que arder (queimar - metáfora do desejo sexual).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28500, 17, 'Aos casados, porém, ordeno - não eu, mas o Senhor - não se separar a esposa do marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28501, 17, 'E, se (vier a) se separar, permaneça não casada, ou se reconcilie com o marido; também o marido não dispense a esposa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28502, 17, 'Aos demais, porém, digo - eu, não o Senhor - se um irmão possui esposa descrente, e ela concorda em morar com ele, não a dispense;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28503, 17, 'E, se uma esposa possui marida descrente, e ele concorda em morar com ela, não dispense o marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28504, 17, 'Pois, o marido descrente é santificado pela esposa; e a esposa descrente é santificada pelo irmão; porquanto, de outro modo, os vossos filhos seriam impuros; agora, porém, são Santos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28505, 17, 'Porém, se o descrente se separa, que se separe; não está escravizado o irmão, ou a irmã, em tais casos; Deus vos chamou para a paz.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28506, 17, 'Pois, como sabes, esposa, se salvarás o marido? Ou, como sabes, marido, se salvarás a esposa?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28507, 17, 'No mais, ande (a pessoa) assim como o Senhor repartiu a cada um, como Deus chamou a cada um. E desse modo ordeno em todas as igrejas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28508, 17, 'Alguém foi chamado circuncidado, não cancele a circuncisão; Alguém foi chamado na incircuncisão, não seja circuncidado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28509, 17, 'A circuncisão nada é, a incircuncisão nada é, mas (sim) a observância dos mandamentos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28510, 17, 'Cada um permaneça na vocação na qual foi chamado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28511, 17, 'Foste chamado (quando era) escravo, não te preocupes; todavia, se também puderes tornar-se livre, antes faze uso (da ocasião).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28512, 17, 'Porquanto, aquele que foi chamado no Senhor, (sendo) escravo, é um liberto do Senhor; de modo semelhante, aquele que foi chamado, sendo livre, é escravo de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28513, 17, 'Fostes comprados por (um) valor, não vos torneis escravos de homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28514, 17, 'Cada qual, irmãos, permaneça naquilo que foi chamado, junto a Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28515, 17, 'A respeito das <b>virgens</b> (jovem casta, noiva, viúva casta), não tenho mandamento do Senhor, mas dou minha opinião, como quem recebeu misericórdia do Senhor para ser (considerado) fiel.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28516, 17, 'Considero, portanto, ser isto bom; por causa da necessidade (do tempo) presente, é bom para o homem ser assim:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28517, 17, 'Estás ligado a mulher? Não procures separação. Estás separado de mulher? Não procures mulher.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28518, 17, 'Todavia, se também casares, não pecaste; e se a <b>noiva</b> (virgem, jovem casta, viúva casta) se casar, não pecou. Mas essas pessoas terão aflição na carne, e eu vos poupo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28519, 17, 'Isto, porém, vos digo, irmãos: O tempo está reduzido. No mais, os que possuem esposas não sejam como os que não possuem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28520, 17, 'E os que pranteiam, (não sejam) como os que não pranteiam; os que se regozijam, (não sejam) como os que não se regozijam; os que compram, (não sejam) como os que não tem posses;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28521, 17, 'os que fazem uso do mundo, (não sejam) como os que não usam o máximo, pois o molde deste mundo está passando (indo embora).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28522, 17, 'Quero, porém, que estejais livres de preocupações. O não casado preocupa-se com as coisas do Senhor, (em) como agradar ao Senhor;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28523, 17, 'O casado, no entanto, preocupa-se com as coisas do mundo, (em) como agradar a esposa,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28524, 17, 'e está dividido. A mulher não casada, e a <b>virgem</b> (jovem casta, noiva, viúva casta), preocupa-se com as coisas do Senhor, a fim de que seja santa tanto no corpo quanto no espírito; Aquela que se casou, porém, preocupa-se com as coisas do mundo, (em) como agradar ao marido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28525, 17, 'Digo isto, todavia, para o vosso próprio benefício, não para colocar sobre vós um laço (cabresto, rede usada para prender animais), mas para digna apresentação e devotamento ao Senhor, sem distrações.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28526, 17, 'Se alguém, porém, pensa que está se portando de modo indigno em relação à sua <b>noiva</b> (virgem, jovem casta, viúva casta), como se estivesse passando do ponto (de casar), sendo necessário acontecer desse modo, (que ele) faça o que deseja, que se casem, (pois) não está pecando.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28527, 17, 'Todavia, aquele que permanece firme no seu coração, não tendo necessidade, mas tendo poder sobre a própria vontade, e decidiu isto no próprio coração - guardar a sua própria <b>noiva</b> (virgem, jovem casta, viúva casta) - fará bem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28528, 17, 'Por conseguinte, tanto procede bem aquele que casa a sua própria <b>noiva</b> (virgem, jovem casta, viúva casta), quanto procede (ainda) melhor aquele que não casa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28529, 17, 'A mulher está ligada ao marido dela por quanto tempo (ele) viver, mas se falecer o marido, está livre para casar-se com quem quiser, (mas) somente no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28530, 17, 'Mais feliz, porém, é (ela) se permanecer assim (viúva), segundo a minha opinião. Penso que também eu tenho o Espírito de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28531, 17, 'Acerca das coisas sacrificadas aos ídolos, sabemos que todos possuímos conhecimento. O conhecimento incha (ensoberbece), mas o amor edifica.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28532, 17, 'Se alguém julga conhecer algo, ainda não conheceu como é necessário conhecer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28533, 17, 'Porém, se alguém ama a Deus, esse (alguém) é conhecido por ele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28534, 17, 'Portanto, a respeito da comida sacrificada aos ídolos, sabemos que “um ídolo nada (é) no mundo” , e que “nenhum Deus (existe), exceto Um”. (Dt 6:4)');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28535, 17, 'Porque, ainda que sejam chamados deuses, seja no céu, seja sobre a terra - como são (chamados) muitos deuses e muitos senhores -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28536, 17, 'para nós, todavia, (há) Um Deus - <b>O Pai</b> - do qual (procede) todas as coisas, e para ele nos (dirigimos); e Um Senhor, Jesus Cristo, através de quem todas as coisas (foram feitas) e por meio de quem nós (nos dirigimos a Deus).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28537, 17, 'Entretanto, não (há) em todos o conhecimento (desse assunto). Alguns, porém, até agora, por costume, como (se realmente fosse) do ídolo, comem as coisas sacrificadas aos ídolos; e a consciência deles, por ser fraca, se contamina.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28538, 17, 'Entretanto, a comida não nos apresenta (para julgamento) a Deus; nem se não comermos nos falta (algo); nem se comermos nos sobra (algo).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28539, 17, 'Vede, porém, que esta vossa liberdade não se torne, de algum modo, tropeço para os fracos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28540, 17, 'Por que, se alguém enxergar a ti, que tens conhecimento, reclinado (à mesa) em templo de ídolo, não será a consciência dele, daquele que é fraco , estimulada a comer as coisas sacrificadas aos ídolos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28541, 17, 'E assim, por causa do teu saber, é destruído o fraco, o irmão pelo qual Cristo morreu.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28542, 17, 'Desse modo, pecando contra os irmãos, golpeando-lhes a consciência fraca, pecais contra o Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28543, 17, 'Portanto, se a comida escandaliza o meu irmão, para sempre, não mais comerei carne, a fim de não escandalizar o meu irmão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28544, 17, 'Não sou livre? Não sou apóstolo? Não vi Jesus, o Nosso Senhor? Porventura, não sois (vós) a minha obra no Senhor?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28545, 17, 'Se não sou apóstolo para os outros, ao menos para vós (eu) sou, porquanto vós sois o selo do meu apostolado no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28546, 17, 'A minha defesa (réplica, contestação) aos que me investigam (termo legal) é esta:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28547, 17, 'Será que não temos (o) direito de comer e de beber?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28548, 17, 'Será que não temos (o) direito de conduzir (no roteiro das viagens) uma irmã, uma esposa, como também (fazem) os demais apóstolos, os irmãos do Senhor, e Cefas?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28549, 17, 'Ou somente eu e Barnabé não temos (o) direito de não trabalhar?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28550, 17, 'Quem serve no exército, alguma vez, (arcando com) o próprio soldo? Quem planta uma vinha e não come o fruto dela? Ou quem apascenta um rebanho e não se alimenta do leito do rebanho?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28551, 17, 'Acaso falo estas coisas “como um homem” (do ponto de vista humano), ou não diz também estas coisas a Lei?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28552, 17, 'Pois na Lei de Moisés está escrito: “Não amordaçarás o boi que debulha (o trigo)”. Porventura, Deus se importa com bois?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28553, 17, 'Ou, (é) por nossa causa, com certeza, que diz (isso)? Por nossa causa, portanto, foi escrito; pois aquele que lavra deve lavrar com esperança, e aquele que debulha (o trigo) (age) com esperança de ter sua parte (participar dos resultados).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28554, 17, 'Se nós semeamos, para vós, as coisas espirituais, (será) grande (coisa) colhermos, de vós, as coisas carnais (metáfora para coisa materiais)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28555, 17, 'Se outros participam (tem sua parte) do vosso direito, não (participam) muito mais nós? Entretanto, não fizemos uso deste direito. Ao contrário, guardamos em segredo (cobrir, ocultar como um telhado), para que não apresentássemos algum obstáculo ao evangelho de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28556, 17, 'Não sabeis que: aqueles que trabalham com as “coisas oferecidas no Templo” (ofertas, sacrifícios) comem as coisas do Templo? Aqueles que servem ao altar participam (retiram sua parte) do altar?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28557, 17, 'Assim também, ordenou o Senhor aos que anunciam o evangelho: viver do evangelho.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28558, 17, 'Eu, porém, não fiz uso de nenhuma dessas coisas. Não escrevi essas coisas para que, dessa forma, aconteça comigo, porque é melhor para mim morrer do que alguém esvaziar (anular) o meu orgulho.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28559, 17, 'Porquanto, se evangelizo, não constitui para mim (motivo de) orgulho, porque me é imposto (como) necessidade; desse modo, ai de mim se não evangelizar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28560, 17, 'Sendo assim, se faço isto voluntariamente, tenho recompensa; se (faço), porém, involuntariamente, me foi confiada administração (encargo, gestão).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28561, 17, 'Qual é, portanto, a minha recompensa? (É) para que, ao evangelizar sem custo, (eu) apresente o evangelho, sem fazer uso do meu direito (garantido) no evangelho.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28562, 17, 'Porque, sendo livre de todos, escravizei-me a todos a fim de ganhar o maior número.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28563, 17, 'Para os Judeus, fiz-me como Judeu, a fim de ganhar os Judeus. Para os que (estão) sujeitos à Lei, (fiz-me) como (alguém) sujeito à Lei - embora eu mesmo não esteja sujeito à Lei - a fim de ganhar os que (estão) sujeitos à Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28564, 17, 'Para os que (estão) sem a Lei, (fiz-me) como (alguém) sem a Lei - embora (eu) não esteja sem a Lei de Deus, mas (esteja) na Lei de Cristo - a fim de ganhar os que (estão) sem a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28565, 17, 'Para os fracos, fiz-me fraco, a fim de ganhar os fracos. Tornei-me tudo para todos, a fim de, por todos os modos, salvar alguns.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28566, 17, 'Faço, porém, todas essas coisas por causa do evangelho, a fim de me tornar co-participante dele (do evangelho).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28567, 17, 'Não sabeis que aqueles que correm no estádio (local da olimpíada grega), conquanto corram todos, somente um recebe o prêmio? Assim, correi para agarrá-lo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28568, 17, 'Todo aquele que compete exerce o auto-controle (em) todas as coisas; eles, no entanto, a fim de receber uma coroa corruptível; nós, porém, uma incorruptível.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28569, 17, 'Portanto, dessa maneira eu corro, não como (alguém) sem meta; dessa maneira dou soco, não como (alguém) que golpeia o ar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28570, 17, 'Ao contrário, esmurro o meu corpo, e o reduzo à escravidão, para que, tendo proclamado (Cristo) a outros, não venha eu mesmo a ser desqualificado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28571, 17, 'Ora, irmãos, não quero que ignoreis que os nossos Patriarcas estiveram todos sob a nuvem (da Glória), e todos atravessaram o mar;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28572, 17, 'todos foram batizados em Moisés, na nuvem (da Glória), e no mar;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28573, 17, 'todos comeram o mesmo alimento espiritual;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28574, 17, 'todos beberam a mesma bebida espiritual, porquanto bebiam da mesma rocha espiritual que (os) acompanha - a rocha era o Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28575, 17, 'Entretanto, Deus não aprovou a maioria deles, pois foram espalhados no deserto.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28576, 17, 'Essas coisas, porém, se tornaram nossos tipos (figuras, modelos, padrões) para que não sejamos cobiçosos de (coisas) más, como eles cobiçaram.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28577, 17, 'Nem vos torneis idólatras, como alguns deles, conforme está escrito: “Assentou-se o povo para comer e beber, e levantaram-se para se divertir”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28578, 17, 'Nem pratiquemos fornicação (relações sexuais ilícitas), como alguns deles fornicaram, e caíram vinte e três mil, em um dia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28579, 17, 'Não submetamos à prova (testar, examinar de modo amplo e profundo) o Cristo, como alguns deles submeteram à prova, e foram destruídos pelas serpentes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28580, 17, 'Nem murmureis, como alguns deles murmuraram, e foram destruídos pelo destruidor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28581, 17, 'Essas coisas ocorreram, tipologicamente, para eles. Todavia, foram escritas para nossa admoestação, para os quais chegaram “<b>as coisas (relativas) ao fim das eras</b>” (conclusão de um processo histórico que aponta para uma finalidade previamente estabelecida por Deus).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28582, 17, 'Desse modo, aquele que considera estar de pé: Olhe! Não caia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28583, 17, 'A tentação (teste, prova) não se apossou de vós, a não ser a (tentação) humana, mas Deus é fiel; ele não permitirá que vós sejais tentados além do que podeis (resistir). Ao contrário, fará junto com a tentação (teste, prova) a saída, para poderdes suportar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28584, 17, 'Portanto, meu amados, fugi da idolatria.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28585, 17, 'Falo como a entendidos; julgai vós (mesmos) o que digo:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28586, 17, 'O cálice da benção, o qual abençoamos, não é a comunhão do sangue de Cristo? O pão que partimos não é a comunhão do corpo de Cristo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28587, 17, 'Porque nós, (mesmo) sendo muitos, somos um só pão e um só corpo; porquanto todos participamos (retiram sua parte, comem) de um só pão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28588, 17, 'Vede Israel - segundo a carne -; os que comem os sacrifícios não são, porventura, os participantes (os que retiram sua parte) do altar?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28589, 17, 'Portanto, o que digo? Que as coisas sacrificadas aos ídolos são alguma coisa? Que o ídolo é alguma coisa?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28590, 17, 'Ao contrário, (digo) que as coisas que sacrificam, (as sacrificam) aos daimones, não a Deus. Não quero, porém, que vós vos torneis comungantes (os que estão em comunhão) dos daimones.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28591, 17, 'Não podeis beber o cálice do Senhor e o cálice dos daimones; não podeis participar da mesa do Senhor e da mesa dos daimones.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28592, 17, 'Ou provocamos inveja no Senhor? Acaso somos mais fortes do que ele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28593, 17, 'Todas as coisas são lícitas, mas nem todas são proveitosas; todas as coisas são lícitas, mas nem todas edificam.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28594, 17, 'Ninguém busque o próprio (proveito), mas (o proveito) do outro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28595, 17, 'Comei de tudo o que é vendido no mercado de carnes, nada questionando em razão da consciência (zelo religioso),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28596, 17, 'pois “a Terra e a plenitude dela (pertencem) ao Senhor”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28597, 17, 'Se algum dos incrédulos vos convidar, e quiserdes ir, comei de tudo o que vos for oferecido, nada questionando em razão da consciência (zelo religioso).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28598, 17, 'Todavia, se alguém vos disser: Isto é coisa sacrificada aos ídolos, não comais, por causa daquele que está informando e da consciência.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28599, 17, 'E digo consciência, porém, não a tua própria, mas (a consciência) do outro. E com que finalidade a minha liberdade é julgada pela consciência alheia?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28600, 17, 'Se eu participo com <b>gratidão</b> (graça), por que sou difamado por aquilo que eu <b>agradeço</b> (dou graças)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28601, 17, 'Sendo assim, quer comais, quer bebais, quer façais algo; fazei todas as coisas para a glória de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28602, 17, 'Tornai-vos sem mancha tanto para Judeus, quanto para Gregos, bem como para a igreja de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28603, 17, 'como eu também, em todas as coisas, agrado a todos, não buscando o meu próprio proveito, mas o (proveito) de muitos, a fim de que sejam salvos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28604, 17, 'Tornai-vos meus imitadores, como eu também de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28605, 17, 'E vos elogio, porque lembrai-vos de mim, em todas as coisas; e retendes as tradições como (eu) as transmiti a vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28606, 17, 'Entretanto, quero que saibais que o Cristo é a cabeça de todo homem; e o homem (é) a cabeça da mulher; e Deus (é) a cabeça de Cristo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28607, 17, 'Todo homem, que está orando ou profetizando, tendo (algo) sobre a cabeça, desonra a sua cabeça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28608, 17, 'Toda mulher, que está orando ou profetizando, com a cabeça descoberta, desonra a sua cabeça; pois é como se estivesse raspada.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28609, 17, 'Portanto, se a mulher não se cobre (referência ao véu na cabeça), tosquie-se. No entanto, se é vergonhoso para a mulher tosquiar-se ou raspar-se, que se cubra (referência ao véu na cabeça).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28610, 17, 'Por conseguinte, por ser imagem e glória de Deus, o homem não deve cobrir a cabeça. A mulher, porém, é glória do homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28611, 17, 'Porque não é o homem (que procede) da mulher, mas a mulher (que procede) do homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28612, 17, 'Também porque não foi o homem criado por causa da mulher, mas a mulher por causa do homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28613, 17, 'Por isso, deve a mulher ter (sinal de) autoridade sobre a cabeça por causa dos anjos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28614, 17, 'Mesmo assim, nem a mulher (tem valor por si só) sem o homem, nem o homem (tem valor por si só) sem a mulher.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28615, 17, 'Pois, como a mulher (procede) do homem, assim também o homem nasce por meio da mulher, todavia, todas as coisas (procedem) de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28616, 17, 'Julgai entre vós mesmos: É adequado a mulher orar a Deus descoberta?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28617, 17, 'A própria natureza não vos ensina que, se o homem tiver cabelos longos, é desonra para ele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28618, 17, 'Por outro lado, se a mulher tiver cabelos longos, é glória para ela? Porque o cabelo lhe foi dado em lugar de cobertura (referência ao véu).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28619, 17, 'Se alguém, porém, se considera um contendedor: nós não temos tal costume, nem as igrejas de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28620, 17, 'Por outro lado, nisto que (a seguir) (vos) prescrevo, não vos elogio, uma vez que vos associais não para o melhor, mas para o pior.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28621, 17, 'Primeiro, porque ouço haver divisões entre vós, e em parte creio.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28622, 17, 'No entanto, é necessário haver também partidos (facções) entre vós, a fim de que se tornem manifestos, entre vós, os aprovados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28623, 17, 'Porquanto, quando vos associais em um mesmo (lugar), não é para comer a ceia do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28624, 17, 'Pois, ao comerdes, cada um toma antecipadamente a sua própria ceia; assim, enquanto um tem fome, o outro se embriaga.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28625, 17, 'Porventura, não tendes casas para comer e beber? Ou desprezais a igreja de Deus, e envergonhais os que nada têm? O que (eu) diria a vós? Eu vos elogiarei? Nisto, (eu) não elogio.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28626, 17, 'Porque eu recebi do Senhor o que também vos transmiti: que o Senhor Jesus, na noite em que foi entregue (traído), tomou o pão,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28627, 17, 'e <b>tendo agradecido</b> (dado graça), (o) partiu e disse: “Isto é o meu corpo, (que é dado) por vós; fazei isto em minha memória”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28628, 17, 'E, de forma semelhante, (tomou) o cálice, depois de cear, dizendo: “Este cálice é a nova aliança em meu sangue; fazei isto, sempre que o beberdes, em minha memória”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28629, 17, 'Porque, sempre que comerdes este pão e beberdes o cálice, anunciais a morte do Senhor, até que (ele) venha.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28630, 17, 'De sorte que, quem comer o pão ou beber o cálice do Senhor, indignamente, será culpado do corpo e do sangue do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28631, 17, 'Examine-se, pois, o homem a si mesmo, e, assim, coma do pão e beba do cálice;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28632, 17, 'porquanto, quem come e bebe sem discernir o corpo, come e bebe juízo para si mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28633, 17, 'Por isso, entre vós, (há) muitos fracos e doentes, e muitos dormem');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28634, 17, 'Porém, se examinássemos a nós mesmos, não seriamos julgados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28635, 17, 'Mas, ao sermos julgados, somos educados (disciplinados) pelo Senhor, a fim de não sermos condenados com o mundo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28636, 17, 'De sorte que, meus irmãos, associando-vos  para comer, esperai uns pelos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28637, 17, 'Se alguém tem fome, coma em casa, a fim de não vos associardes para juízo. Quanto às demais coisas, (eu) as ordenarei quando for (até vós).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28638, 17, 'A respeito dos (dons, dádivas, doação da caridade) espirituais, irmãos, não quero que ignoreis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28639, 17, 'Sabeis que, quando éreis Gentios, como se fosseis guiados, éreis conduzidos para os ídolos mudos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28640, 17, 'Por isso, vos faço saber que ninguém, falando pelo Espírito de Deus, diz: “Anátema Jesus”. E ninguém pode dizer: “Senhor Jesus”; senão, pelo Espírito Santo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28641, 17, 'Ora, há <b>repartição</b> (ato de dividir o todo e distribuir as partes) de <b>dons</b> (dádiva, doação da caridade), mas o Espírito é o mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28642, 17, 'Há <b>repartição</b> (ato de dividir o todo e distribuir as partes) de serviços, mas o Senhor é o mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28643, 17, 'Há <b>repartição</b> (ato de dividir o todo e distribuir as partes) de realizações, mas é o mesmo Deus que realiza todas as coisas em todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28644, 17, 'A manifestação do Espírito é dada a cada um para o benefício (comum).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28645, 17, 'Porquanto, a um é dada, por meio Espírito, a palavra de sabedoria; a outro é dada, segundo o mesmo Espírito, a palavra de conhecimento;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28646, 17, 'a outro (é dada), no mesmo Espírito, a fé; a outro (é dado), neste Espírito, os  <b>dons</b> (dádiva, doação da caridade) de curas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28647, 17, 'a outro as “operações de poderes” (realização de fatos extraordinários, ditos sobrenaturais); a outro a profecia; a outro o discernimento de espíritos; a outro os gêneros de línguas; a outro a interpretação de línguas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28648, 17, 'mas um só, e o mesmo Espírito, realiza todas estas coisas, <b>repartindo</b> (ato de dividir o todo e distribuir as partes), individualmente, a cada um conforme (ele) quer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28649, 17, 'Porque, assim como o corpo é um só, mas têm muitos membros, e todos os membros do corpo, embora sendo muitos, constituem um (só) corpo, assim também (é) o Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28650, 17, 'Assim também, em um só Espírito, todos nós fomos batizados em um (só) corpo, quer Judeus, quer Gregos, quer escravos, quer livres. E a todos (nós) foi dado beber de um (só) Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28651, 17, 'Porquanto, também o corpo não é um (só) membro, mas muitos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28652, 17, 'Se o pé disser: “Porque não sou sou mão, não sou do corpo”. Nem por isso (ele) não é do corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28653, 17, 'Se o ouvido disser: “Porque não sou sou olho, não sou do corpo”. Nem por isso (ele) não é do corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28654, 17, 'Se todo o corpo (for) olho, onde a audição? Se todo (o corpo for) audição, onde o olfato?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28655, 17, 'Agora, porém, Deus colocou os membros no corpo, cada um segundo ele quis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28656, 17, 'Todavia, se todos fossem um só membro, onde o corpo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28657, 17, 'Agora, porém, (há) muitos membros, mas um (só) corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28658, 17, 'E não pode o olho dizer à mão: “Não tenho necessidade de ti”. Ou, por sua vez, a cabeça (dizer) aos pés: “Não tenho necessidade de vós”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28659, 17, 'Pelo contrário, os membros do corpo que parecem ser os mais fracos são muito necessários.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28660, 17, 'E aqueles (membros) do corpo que consideramos ser os menos honrosos, a estes cobrimos (vestir, tampar com um pano ao redor) com mais abundante honra; e os nossos (membros) indecorosos têm mais abundante decoro (no ato de vestir, cobrir).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28661, 17, 'Todavia, os nossos (membros) decorosos não têm necessidade (de cuidados no ato de vestir, cobrir). Mas Deus harmonizou (mesclar, combinar as partes) o corpo, dando maior honra ao (membro) carente,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28662, 17, 'a fim de que não haja cisão no corpo; mas que os membros tenham o mesmo cuidado uns pelos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28663, 17, 'Assim, se um membro sofre, todos sofrem com ele; se um membro é glorificado, todos os membros se alegram com ele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28664, 17, 'Ora, vós sois o corpo de Cristo; e, individualmente, (sois) membros (desse corpo).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28665, 17, 'E a uns estabeleceu Deus na igreja, primeiramente apóstolos; em segundo (lugar) profetas; em terceiro (lugar) mestres; depois “detentores de poderes” (pessoas que realizam fatos extraordinários, ditos sobrenaturais); depois <b>dons</b> (dádiva, doação da caridade) de curas; (depois) os que socorrem, os que comandam, gêneros de línguas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28666, 17, 'Acaso, todos (são) apóstolos? Porventura, todos (são) profetas? Todos (são) mestres? Será que todos (são) “detentores de poderes” (pessoas que realizam fatos extraordinários, ditos sobrenaturais)?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28667, 17, 'Porventura, todos possuem <b>dons</b> (dádiva, doação da caridade) de curas? Acaso, todos falam em línguas? Todos interpretam?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28668, 17, 'Desejai ardentemente, porém, os melhores <b>dons</b> (dádiva, doação da caridade). E (eu) vos mostro um caminho ainda mais excelente.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28669, 17, 'Ainda que eu fale nas línguas dos homens e dos anjos, se não tiver <b>amor</b>, tornei-me bronze que soa ou o címbalo que retine.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28670, 17, 'Ainda que eu tenha profecia e conheça todos os mistérios e toda a ciência (conhecimento); ainda que eu tenha toda a fé, a ponto de remover montes, se não tiver <b>amor</b>, nada sou.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28671, 17, 'E ainda que eu reparta todos os meus bens, e ainda que entregue o meu próprio corpo para que me glorie (martírio), se não tiver <b>amor</b>, nada (disso) me aproveita.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28672, 17, 'O <b>amor</b> é paciente; o <b>amor</b> é bondoso (*afável, dócil*); não é ciumento, não se vangloria, não se incha (ensoberbece);');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28673, 17, 'não é indecoroso, não busca os seus próprios (*interesses*), não se torna irado, não leva em conta o mal;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28674, 17, 'não se alegra com a injustiça, mas se regozija com a verdade.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28675, 17, 'Tudo <b>tolera</b> (*literalmente “encobre”; sofre em silêncio, “passa por cima”*), tudo crê, tudo espera, tudo suporta.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28676, 17, 'O <b>amor</b> jamais cai prostrado (cair, desmoronar); mas, se (há) profecias, serão abolidas; se (há) línguas, cessarão; se (há) conhecimento, será abolido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28677, 17, 'Porque, em fragmento, conhecemos; e, em fragmento, profetizamos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28678, 17, 'Quando, porém, vier o que é <b>completo</b> (*pleno, finalizado, concluído*), as coisas fragmentadas serão abolidas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28679, 17, 'Quando (eu) era criança, falava como criança, pensava como criança, raciocinava como criança; quando me tornei homem, aboli as coisas de criança.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28680, 17, 'Porque, agora, vemos através de espelho, em enigma, mas (veremos) face à face;  agora, conheço em fragmento, mas então conhecerei (*completamente*), como também sou plenamente conhecido.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28681, 17, 'Agora, pois, permanecem a fé, a esperança, e o <b>amor</b>, estes três; porém, o maior destes é o <b>amor</b>.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28682, 17, 'Segui o amor, desejai ardentemente os (*dons, dádivas, doação da caridade*) espirituais, mas muito mais que profetizeis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28683, 17, 'Pois quem fala em (outra) língua não fala a homens, mas a Deus, visto que ninguém ouve (entende), porquanto em espírito fala mistérios.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28684, 17, 'Mas o que profetiza fala aos homens para edificação, exortação e consolação (conforto, encorajamento, estímulo).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28685, 17, 'O que fala em (outra) língua edifica a si mesmo, mas o que profetiza edifica a igreja.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28686, 17, 'Quero que todos vós faleis em (outras) línguas, mas muito mais que profetizeis; pois o que profetiza é superior ao que fala em (outras) línguas, a menos que interprete, a fim de que a igreja receba edificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28687, 17, 'Agora, porém, irmãos, se (eu) for até vós, falando em (outras) línguas, que vos aproveitaria, se (eu) não vos falar por meio de revelação, ou conhecimento, ou profecia ou ensino?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28688, 17, 'De modo semelhante, as coisas inanimadas, quando emitem som, seja flauta ou cítara, se não apresentar distinção nos sons, como será conhecido o que é tocado na flauta, ou o que é tocado na cítara?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28689, 17, 'Pois também se a trombeta emitir som incerto, quem se prepará para a batalha?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28690, 17, 'Assim, também vós, se não emitirdes, com a língua, uma palavra inteligível como será entendido aquilo que é falado? Porquanto, estareis falando para o ar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28691, 17, 'É possível existirem tantos gêneros de vozes no mundo! No entanto, nenhum sem sentido (lit. sem voz).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28692, 17, 'Portanto, se (eu) não souber o significado da voz, serei um bárbaro para aquele que fala, e aquele que fala será um bárbaro para mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28693, 17, 'Assim, também vós, que sois zelosos de (*dons, dádivas, doação da caridade*) espirituais, desejai ardentemente (esses dons) para a edificação da igreja, a fim de que os tenhais sobejamente.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28694, 17, 'Por conseguinte, o que fala em (outra) língua ore para que (também) interprete.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28695, 17, 'Pois se (eu) orar em (outra) língua, o meu espírito estará orando, mas a minha mente estará improdutiva.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28696, 17, 'Portanto, o que farei? Orarei com o espírito, mas também orarei com a mente; cantarei com o espírito, mas também cantarei com a mente.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28697, 17, 'Do contrário, se abençoardes (somente) em espírito, como dirá “Amém” aquele que ocupa o lugar de inculto (sem instrução), depois do teu <b>agradecimento</b> (ação de graças)? Porque aquilo que dizes (ele) não sabe.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28698, 17, 'Assim, tu <b>agradeces</b> (ação de graças) bem, mas o outro não é edificado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28699, 17, '<b>Agradeço</b> (ação de graças) a Deus, (porque) falo em (outras) línguas muito mais do que todos vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28700, 17, 'Todavia, na igreja, quero falar cinco palavras com a minha mente, a fim de também instruir aos outros, do que dez mil palavras em (outra) língua.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28701, 17, 'Irmãos, não sejais crianças no modo de pensar; na malícia, sede crianças, mas no modo de pensar sede maduros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28702, 17, 'Na Lei, está escrito: “Falarei a este povo por pessoas de outras línguas, mas nem assim me ouvirão”, diz o Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28703, 17, 'De modo que, as línguas são sinal não para aqueles que crêem, mas para os que não crêem. Por outro lado, a profecia não (é sinal) para aqueles que não crêem, mas para os que crêem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28704, 17, 'Portanto, se toda a igreja se reunir no mesmo (lugar), e todos falarem línguas, quando entrarem os incultos e os que não crêem, não dirão que estais loucos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28705, 17, 'Porém, se todos profetizarem, quando entrar alguém que não crê ou (é) inculto, será convencido por todos, e julgado por todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28706, 17, 'As coisas secretas do coração dele se tornarão manifestas; e, assim, “caindo sobre o rosto” (prosternando-se), adorará a Deus, anunciando: “Verdadeiramente, Deus está entre nós”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28707, 17, 'Portanto, o que fazer, irmãos? Quando vos reunis, um tem Salmo, (outro) tem ensino, (aquele) tem revelação, (este) tem língua, e (outro) interpretação - (que) todas estas coisas sejam feitas para edificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28708, 17, 'Se alguém fala em língua, (que seja) por dois ou no máximo três, e um de cada vez; e (haja) um intérprete.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28709, 17, 'Mas, se não houver intérprete, fique calado na igreja; fale para si mesmo e para Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28710, 17, '(Quanto aos) profetas, falem dois ou três, e outros julguem (avaliar, examinar).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28711, 17, 'Se, porém, for revelado (algo) a outro (que esteja) assentado (na reunião), cale-se o primeiro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28712, 17, 'Porque todos podeis profetizar, um após o outro, a fim de que todos aprendam e todos sejam consolados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28713, 17, 'Porquanto os “espíritos de profetas” (que se manifestam pelos profetas) estão subordinados aos profetas,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28714, 17, 'pois Deus não é de desordem, mas de paz. Como em todas as igrejas dos Santos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28715, 17, 'calem-se as mulheres na igreja, porque não não lhes é permitido falar;  ao contrário, estejam subordinadas, conforme diz também a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28716, 17, 'Todavia, se algo desejam aprender, interroguem, em casa, os (seus) próprios maridos; pois é indecoroso para a mulher falar na igreja.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28717, 17, 'Porventura, a palavra de Deus veio (se originou) de vós, ou chegou somente para vós?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28718, 17, 'Se alguém considera ser profeta ou espiritual, reconheça que as coisas que vos escrevo são mandamento do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28719, 17, 'E, se alguém ignorar (este mandamento), será ignorado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28720, 17, 'Sendo assim, meus irmãos, desejai ardentemente o profetizar, e não impeçais o falar em línguas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28721, 17, 'Todas essas coisas, porém, sejam feitas com decoro e com ordem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28722, 17, 'Irmãos, vos dei a conhecer o evangelho - o que vos evangelizei, o que recebestes (tradição oral), e no qual estais firmes (estar de pé) -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28723, 17, 'através do qual também sois salvos, se retiverdes aquela palavra que vos evangelizei, a menos que crestes em vão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28724, 17, 'Em primeiro lugar, portanto, vos entreguei o que também recebi: que Cristo morreu pelos nossos pecados, segundo as Escrituras;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28725, 17, 'que foi sepultado e ressuscitou (foi erguido) no terceiro dia, segundo as Escrituras;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28726, 17, 'que se tornou visível a Cefas, e depois aos doze.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28727, 17, 'Então, se tornou visível a mais de quinhentos irmãos, de uma só vez, dos quais a maioria permanece (viva) até agora, embora alguns tenham adormecido (metáfora para “morrer”).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28728, 17, 'Depois tornou-se visível a Tiago, e a todos os apóstolos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28729, 17, 'Por último, depois de todos - como a alguém nascido fora do tempo - tornou-se visível também a mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28730, 17, 'Porquanto, eu sou o menor dos apóstolos, não sou o bastante para ser chamado apóstolo, porque persegui a igreja de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28731, 17, 'No entanto, por <b>caridade</b> (graça) de Deus, sou o que sou; e a <b>caridade</b> (graça) dele, em mim, não se tornou vazia (vã). Ao contrário, labutei mais abundantemente que todos eles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28732, 17, 'Portanto, seja eu ou sejam eles, assim proclamamos e assim crestes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28733, 17, 'Sendo assim, se é proclamado que Cristo ressuscitou (foi erguido) dentre os mortos, como alguns dentre vós dizem que não há ressurreição de mortos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28734, 17, 'E, se não há ressurreição de mortos, nem Cristo foi ressuscitado (foi erguido).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28735, 17, 'E, se Cristo não foi ressuscitado (foi erguido), então a nossa proclamação é vazia (vã); também (é) vazia a vossa fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28736, 17, 'Somos também considerados falsas testemunhas de Deus, porque testemunhamos contra Deus, (ao dizer) que (ele) ressuscitou (ergueu) o Cristo, a quem (ele) não teria ressuscitado - se de fato os mortos não são ressuscitados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28737, 17, 'Porquanto, se os mortos não são <b>ressuscitados</b> (erguidos), nem o Cristo foi ressuscitado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28738, 17, 'Porém, se Cristo não foi <b>ressuscitado</b> (foi erguido), a vossa fé é inútil; ainda estais em vossos pecados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28739, 17, 'Por conseguinte, os que adormeceram (metáfora para “morrer”) em Cristo, pereceram também.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28740, 17, 'Se estamos esperando em Cristo somente nesta vida, somos os mais miseráveis de todos os homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28741, 17, 'Agora, porém, (que) Cristo foi <b>ressuscitado</b> (foi erguido) dentre os mortos, (tornou-se) primícias dos que adormeceram (metáfora para “morrer”).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28742, 17, 'Porque, assim como a morte (veio) por um homem, assim também a ressurreição dos mortos (veio) por um homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28743, 17, 'Pois, assim como todos morrem em Adão, assim também todos serão vivificados (tornados vivos) em Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28744, 17, 'Cada qual, porém, na sua própria ordem (sequência): as primícias, Cristo;  depois, os que são de Cristo, na <b>presença</b> (vinda, advento) dele;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28745, 17, 'Então, o <b>término</b> (*conclusão de um processo histórico que aponta para uma finalidade previamente estabelecida por Deus*), quando (ele) entregar o Reino ao Deus e Pai; quando abolir todo governo, toda autoridade, todo poder.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28746, 17, 'Portanto, é necessário que ele reine até que coloque todos os inimigos sob os seus pés.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28747, 17, 'O último inimigo está sendo abolido: a morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28748, 17, 'Porque “todas as coisas subordinou ordenadamente debaixo dos seus pés”. E quando diz “todas as coisas subordinou ordenadamente”, certamente, exclui aquele que tudo lhe subordinou.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28749, 17, 'Quando, porém, todas as coisas lhe forem subordinadas, então, ele mesmo, o Filho, será subordinado àquele que lhe subordinou todas as coisas, a fim de que Deus seja todas as coisas em todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28750, 17, 'Em razão disso, que farão os batizados pelos mortos? Se, absolutamente, mortos não são <b>ressuscitados</b> (*erguidos*), por que são  também batizados por eles?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28751, 17, 'Por que nós também nos colocamos em perigo toda hora?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28752, 17, 'A cada dia pereço, tão certo, irmãos, quanto a vanglória - que tenho em Cristo Jesus, nosso Senhor - por vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28753, 17, 'Se, como homem, lutei com feras em Éfeso, qual o ganho (proveito, vantagem) para mim? Se mortos não são <b>ressuscitados</b> (*erguidos*), “*comamos e bebamos, pois morremos amanhã*”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28754, 17, 'Não sejais enganados: “más companhias corrompem os bons costumes” (Verso do poeta Menandro).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28755, 17, 'Sejais sóbrios, de modo justo, e não pequeis, porque alguns ignoram a Deus - falo para a vossa vergonha.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28756, 17, 'Mas alguém dirá: como são <b>ressuscitados</b> (*erguidos*) os mortos? E como que tipo de corpo (eles) vêm?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28757, 17, 'Tolo! O que semeias não é vivificado se não morrer;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28758, 17, 'e, aquilo que semeias, não semeias o corpo que virá a ser, mas o grão nu, caso seja de trigo ou de algum dos demais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28759, 17, 'E Deus lhe dá o corpo como lhe aprouver - a cada uma das sementes o seu próprio corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28760, 17, 'Nem toda carne é a mesma carne, mas uma é a (carne) de homens, outra a carne de animais, outra a carne de aves, outra a dos peixes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28761, 17, 'E (há) corpos celestiais e corpos terrestres, mas uma é a glória dos celestiais, e outra a dos terrestres.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28762, 17, 'Uma (é) a glória do sol, outra a glória da lua, e outra a glória das estrelas; pois uma estrela difere de outra estrela em glória.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28763, 17, 'Assim também a ressurreição dos mortos: semeado em deterioração, <b>ressuscitado</b> (*erguido*) em não deterioração;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28764, 17, 'semeado em desonra, <b>ressuscitado</b> (*erguido*) em glória; semeado em fraqueza, <b>ressuscitado</b> (*erguido*) em poder;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28765, 17, 'semeado corpo <b>anímico</b>, <b>ressuscitado</b> (*erguido*) corpo espiritual. Se há corpo <b>anímico</b>, também há espiritual.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28766, 17, 'Pois assim está escrito: “O primeiro homem, Adão, tornou-se <b>alma</b> vivente”, o último Adão espírito vivificante.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28767, 17, 'Todavia, não (vem) primeiro o espiritual, mas o <b>anímico</b>; depois o espiritual.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28768, 17, 'O primeiro homem, (proveniente) da terra, (é) terreno; o segundo homem (é proveniente) do céu.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28769, 17, 'Tal qual o terreno, tais (são) também os terrenos; tal qual o celestial, tais (são) também os celestiais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28770, 17, 'E, assim como portamos a imagem do terreno, também portaremos a imagem do celestial.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28771, 17, 'E digo isto, irmãos, que carne e sangue não podem herdar o Reino de Deus, nem a deterioração herda a não deterioração.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28772, 17, 'Eis que vos digo um mistério: Nem todos dormiremos, mas todos seremos transformados;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28773, 17, 'em um átimo, em um piscar de olhos, na última trombeta; porquanto soará a trombeta, os mortos serão <b>ressuscitados</b> (*erguidos*) não deteriorados, e nós seremos transformados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28774, 17, 'É necessário, porém, este (corpo) deteriorável revestir-se da não deterioração, e este (corpo) mortal revestir-se da imortalidade.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28775, 17, 'E, quando este (corpo) deteriorável revestir-se da não deterioração, e este (corpo) mortal revestir-se da imortalidade, então sucederá a palavra que foi escrita: “*Tragada foi a morte pela vitória.*');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28776, 17, '*Onde (está), ó morte, a tua vitória? Onde (está), ó morte, o teu ferrão (aguilhão)?*”');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28777, 17, 'O ferrão da morte (é) o pecado, e o poder do pecado (é) a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28778, 17, '<b>Gratidão</b> (graça) a Deus, que nos dá a vitória, através de nosso Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28779, 17, 'Desse modo, meus amados irmãos, sede firmes, inabaláveis, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão (vazio) no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28780, 17, 'A respeito da coleta para os Santos, assim como ordenei às igrejas da Galácia, fazei vós também do mesmo modo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28781, 17, 'No primeiro sábado, cada um de vós reserve junto a si mesmo, entesourando consoante o que tiver prosperado, a fim de que não ocorram coletas (somente) no momento em que (eu) for.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28782, 17, 'E, quando (eu) chegar, aqueles que tiverdes aprovado, (eu) os enviarei, mediante epístolas, para levar a vossa <b>caridade</b> (graça) à Jerusalém;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28783, 17, 'se for apropriado que eu também vá, (eles) irão comigo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28784, 17, 'E virei até vós, quando (eu) atravessar a Macedônia, porque (devo) atravessar a Macedônia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28785, 17, 'Permanecerei junto a vós e, talvez, também passarei o inverno, a fim de que vós me acompanheis onde quer que eu for.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28786, 17, 'Portanto, não quero vos ver agora, de passagem, pois espero permanecer algum tempo junto a vós, se o Senhor permitir.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28787, 17, 'Permanecerei, entretanto, em Éfeso até o Pentecostes;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28788, 17, 'porquanto se abriu para mim uma porta, grande e eficaz, bem como muitos adversários.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28789, 17, 'E, se Timóteo for, vede que esteja sem temor junto de vós, pois realiza a obra do Senhor, como também eu;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28790, 17, 'ninguém, pois, o despreze. Mas encaminhai-o em paz, para que venha ter comigo, visto que o espero com os irmãos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28791, 17, 'A respeito do irmão Apolo, muito o exortei para que fosse até vós, com os irmãos, mas de modo algum era da vontade dele ir agora; irá, todavia, quando tiver oportunidade.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28792, 17, 'Vigiai, ficai firmes na fé, sede corajosos, sede fortes.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28793, 17, 'Todas as vossas coisas ocorram no amor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28794, 17, 'E vos exorto, irmãos - sabeis que a casa de Estéfanas são as primícias da Acaia e que se dedicaram ao serviço dos Santos -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28795, 17, 'para que vós também vos subordineis a esses, e a todo aquele que está cooperando e labutando.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28796, 17, 'Alegro-me com a vinda de Estéfanas, de Fortunato e de Acaico, porque eles supriram a vossa ausência;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28797, 17, 'deram descanso ao meu espírito e ao vosso. Reconhecei, portanto, a esses.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28798, 17, 'As igrejas da Ásia vos saúdam. Áquila e Prisca muito vos saúda, juntamente com a igreja que (há) na casa deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28799, 17, 'Todos os irmãos vos saúdam. Saudai uns aos outros com ósculo santo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28800, 17, 'A saudação com minha mão: “<b>de Paulo</b>”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28801, 17, 'Se alguém não ama o Senhor, seja anátema. <b>Maranatha</b> (Senhor, vem\!)');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28802, 17, 'A <b>caridade</b> (graça) do Senhor Jesus (seja) convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28803, 17, 'O meu amor (esteja) com todos vós, em Cristo Jesus.');