INSERT INTO verse_text (verse_id, version_id, text) VALUES (27934, 17, 'Paulo, servo  do Cristo  Jesus, chamado apóstolo, separado  para o Evangelho de Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27935, 17, 'o qual foi  previamente prometido através dos seus Profetas, nas Escrituras sagradas,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27936, 17, 'a respeito do seu filho, gerado da  semente de David,  segundo a carne,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27937, 17, 'investido como filho de Deus, em poder, segundo o espírito de santidade, pela ressurreição  dos mortos - Jesus Cristo, nosso Senhor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27938, 17, 'por quem recebemos graça  e apostolado, para obediência da fé, entre todas as nações,  no interesse do seu nome,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27939, 17, 'entre as quais (nações), também vós, de Jesus Cristo, sois chamados,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27940, 17, 'a todos que estais em Roma, amados de Deus, chamados santos: Graça e Paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27941, 17, 'Primeiramente, dou graças a meu Deus, por meio de Jesus Cristo, por todos vós, porque a vossa fé é proclamada  em todo o mundo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27942, 17, 'Pois Deus, a quem  presto culto, em meu espírito, no Evangelho do seu filho, me é testemunha de que incessantemente faço menção de vós,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27943, 17, 'rogando sempre em minhas orações que, finalmente, agora, de algum modo, segundo a vontade de Deus, eu  tenha êxito em ir até vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27944, 17, 'Pois  anseio intensamente vos ver, a fim de repartir  convosco dom  referente ao espírito, para vos fortalecer,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27945, 17, 'isto é, para entre vós sermos consolados conjuntamente, pela fé uns dos outros, vossa e também minha.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27946, 17, 'Não quero, porém, irmãos, que ignoreis que muitas vezes me propus  ir até vós - mas até agora fui impedido  - para obter algum fruto, tanto entre vós quanto entre as demais nações.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27947, 17, 'Pois sou devedor a gregos e a bárbaros, a sábios e a tolos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27948, 17, 'Quanto a mim, portanto, {estou} pronto para vos evangelizar em Roma.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27949, 17, 'Pois não me envergonho do Evangelho, que é poder de Deus para salvação de todos que crêem, primeiro Judeus, mas também Gregos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27950, 17, 'Porque nele a justiça de Deus é revelada, a partir da fé para a fé, conforme está escrito: "O Justo, porém, viverá de fé" .');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27951, 17, 'Assim, a ira de Deus se revela, do céu, sobre toda a impiedade e injustiça dos homens que retêm a verdade na injustiça,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27952, 17, 'porque o que se pode conhecer de Deus está manifesto entre eles, pois Deus se manifestou a eles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27953, 17, 'Porque os (atributos) invisíveis dele – tanto o seu eterno poder quanto sua divindade –desde a criação do cosmos, pelas coisas feitas, são percebidos e entendidos, para eles serem indesculpáveis,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27954, 17, 'porquanto, tendo conhecido a Deus, não o glorificaram como Deus, nem lhe deram graças, mas tornaram-se vãos em seus discursos e obscureceu-se o insensato coração deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27955, 17, 'Afirmando serem sábios, tornaram-se tolos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27956, 17, 'e mudaram a glória do Deus imperecível em semelhança de imagem de homem perecível, e de aves, quadrúpedes e répteis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27957, 17, 'Por isso Deus os entregou aos desejos dos seus corações, para a impureza da desonra mútua dos seus corpos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27958, 17, 'Os quais trocaram a verdade de Deus pela mentira, reverenciaram e serviram à criatura em lugar do Criador, que é bendito para sempre, amém.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27959, 17, 'Por isso Deus os entregou à experiência  de desonra, pois suas mulheres trocaram as relações  naturais pelo que é contrário à natureza;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27960, 17, 'também, de forma semelhante, os homens, deixando as relações naturais com a mulher, arderam em desejo uns pelos outros, praticando atos vergonhosos, homens com homens, recebendo a retribuição do próprio erro em si mesmos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27961, 17, 'E como não julgaram adequado ter conhecimento sobre Deus, Deus os entregou à sua mente incapaz de julgar, para fazerem as coisas que não convém:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27962, 17, 'cheios de toda a injustiça, perversidade, ganância, vício; repletos de inveja, de homicídio, de rivalidade, malícia  e dissimulação ; fofoqueiros,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27963, 17, 'caluniadores,  inimigos de Deus, insolentes, arrogantes, orgulhosos,  inventores de males,  desobedientes aos pais,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27964, 17, 'sem juízo, sem lealdade, sem afeto, sem compaixão;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27965, 17, 'os quais, conhecendo o juízo de Deus - os que praticam tais coisas são dignos de morte - não somente fazem essas coisas, mas concordam com os que as praticam.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27966, 17, 'Por isso, ó homem - todo aquele que julga - és indesculpável, pois, quando julgas o outro, a ti mesmo te condenas, uma vez que praticas as mesmas coisas que julgas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27967, 17, 'Sabemos que o juízo de Deus, segundo a verdade, é contrário aos que tais coisas praticam');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27968, 17, 'E supões, ó homem - aquele que julga quem pratica tais coisas, mas faz as mesmas - que tu escaparás do juízo de Deus?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27969, 17, 'Ou desprezas a riqueza da sua bondade, tolerância e longanimidade, ignorando que a bondade de Deus conduz à conversão?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27970, 17, 'Mas, segundo o teu endurecimento  e coração impenitente, entesouras ira para ti mesmo no dia da ira e da revelação do justo julgamento de Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27971, 17, 'o qual retribuirá a cada um segundo as suas obras:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27972, 17, 'vida eterna aos que, com perseverança na boa obra, buscam glória, honra e o imperecível;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27973, 17, 'ira e indignação aos que são de contenda e desobedientes à verdade, mas obedientes à injustiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27974, 17, 'Tribulação e angústia sobre toda a alma do homem que produz o mal, primeiro ao Judeu, mas também ao Grego;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27975, 17, 'Glória, honra e paz a todos que realizam o bom, primeiro ao Judeu, mas também ao Grego;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27976, 17, 'Pois não há parcialidade perante Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27977, 17, 'Os que sem Lei pecaram, sem Lei também perecerão, mas os que na Lei pecaram, através da Lei serão julgados.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27978, 17, 'Assim, não são os ouvintes da Lei que são justos perante Deus, mas são os praticantes da Lei que serão declarados justos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27979, 17, 'Desse modo, sempre que os Gentios - que não possuem Lei - fizerem, por condição natural, as coisas da Lei, eles - que não possuem Lei - para si mesmos são Lei;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27980, 17, 'os quais manifestam a obra da Lei, escrita em seus corações, co-testemunhando a sua consciência, entre pensamentos que, mutuamente, acusam e defendem,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27981, 17, 'no dia em que Deus julga as coisas ocultas dos homens, segundo o meu evangelho, mediante Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27982, 17, 'Se tu te nomeias Judeu, te apoias na Lei, vangloria-te em Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27983, 17, 'conheces a vontade, aprovas as coisas excelentes - sendo instruído na Lei -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27984, 17, 'estás persuadido de seres, tu mesmo, guia de cegos, luz na treva,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27985, 17, 'educador de ignorantes, mestre de crianças - possuindo na Lei a modelagem do conhecimento e da verdade -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27986, 17, 'no entanto, o que ensinas a outrem, não ensinas a ti mesmo? Aquele que proclama "não furtar", furta?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27987, 17, 'Aquele que diz "não adulterar", adultera? Aquele que abomina as coisas dos ídolos, saqueia templos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27988, 17, 'Aquele que se gloria na Lei, desonra a Deus pela transgressão da Lei?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27989, 17, 'Pois, como está escrito "O nome de Deus é blasfemado entre os gentios por vossa causa".');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27990, 17, 'Ora, se por um lado a circuncisão é proveitosa, se cumprires a Lei, por outro lado, se fores um transgressor da Lei, a tua circuncisão se tornou incircuncisão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27991, 17, 'Portanto, se a incircuncisão observa os preceitos da Lei, a sua incircuncisão não será considerada circuncisão?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27992, 17, 'E, se aquele que é incircunciso, por natureza, cumpre a Lei, não julgará a ti, transgressor da Lei, não obstante a letra e a circuncisão?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27993, 17, 'Desse modo, não é judeu quem é na manifestação, nem é circuncisão a que é na manifestação da carne,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27994, 17, 'mas quem é judeu no oculto, e a que é circuncisão no coração, em espírito, não na letra, cujo louvor não seja de humanos, mas de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27995, 17, 'Qual pois a vantagem do judeu, ou qual o proveito da circuncisão?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27996, 17, 'Muita, sob todos os aspectos. Primeiramente, porque lhes foram confiados os oráculos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27997, 17, 'Assim, que importa se alguns não creram? Porventura, a descrença deles anulará a fidelidade de Deus?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27998, 17, 'De modo nenhum! Ao contrário, seja Deus verdadeiro, porém, mentiroso (seja) todo homem, como está escrito: "Para que sejas justificado nas tuas palavras, e venças quando fores julgado".');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (27999, 17, 'Mas, se a nossa justiça ressalta a justiça de Deus, que diremos? Acaso, Deus - o que aplica a ira - é injusto? Falo como homem\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28000, 17, 'De modo nenhum! Do contrário, como Deus julgará o mundo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28001, 17, 'Todavia, se pela minha mentira, aumentou a verdade de Deus, para sua glória, por que também eu, como pecador, ainda sou julgado?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28002, 17, 'E por que não dizermos, como alguns, caluniosamente, afirmam que dizemos: Façamos as coisas más para que venham as coisas boas? A condenação destes é justa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28003, 17, 'Então, o que se conclui? Temos primazia? Não, absolutamente, pois já demonstramos que todos, tanto judeus quanto gregos, estão debaixo do pecado,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28004, 17, 'Conforme está escrito:  Não há justo, nem um sequer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28005, 17, 'Não há quem entenda,  Não há quem busque a Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28006, 17, 'Todos se extraviaram, juntos se tornaram inúteis, não há quem pratique a bondade, nem um sequer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28007, 17, 'A garganta deles é sepulcro aberto, com suas línguas enganaram, veneno de áspides estão sob seus lábios,"');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28008, 17, 'cujas bocas estão repletas de maldição e amargura.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28009, 17, 'Os seus pés são velozes para derramar sangue.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28010, 17, 'Há destruição e miséria em seus caminhos');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28011, 17, 'Não conheceram o caminho da paz.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28012, 17, 'Não há termor à Deus diante dos seus olhos"');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28013, 17, 'Ora, sabemos que as coisas que a Lei diz, aos que estão sob a Lei fala, para que toda boca seja fechada, e todo o mundo se torne indiciado/denunciado perante Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28014, 17, 'porque nenhuma carne será justificada (declarada justa), perante ele, pelas obras da Lei, uma vez que pela Lei há pleno conhecimento do pecado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28015, 17, 'Mas, agora, testemunhada pela Lei e pelos Profetas, a justiça de Deus está manifesta para além da Lei -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28016, 17, 'justiça de Deus pela fé (fidelidade) em Jesus Cristo - para todos que tem fé; pois não há distinção,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28017, 17, 'visto que todos pecaram e estão inaptos à glória de Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28018, 17, 'são justificados por dádiva através da sua graça (caridade), pela redenção no Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28019, 17, 'O qual Deus ofereceu (no) propiciatório para comprovação da sua justiça,  por meio da fé no sangue dele (Jesus),  para remissão dos pecados previamente ocorridos com tolerância/paciência de Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28020, 17, 'para a demonstração da sua justiça no tempo/período presente, para ele mesmo ser justo e o justificador daquele que é proveniente da fé de Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28021, 17, 'Onde, pois, a jactância? Foi excluída. Por que tipo de Lei? Das obras? Não, mas pela Lei da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28022, 17, 'Portanto, consideramos que o homem é justificado pela fé, sem obras da Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28023, 17, 'Deus é, porventura, somente dos judeus? Não. É também dos gentios? Sim, também dos gentios,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28024, 17, 'visto que Deus é um, o qual justificará a circuncisão a partir da fé, e a incircuncisão através da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28025, 17, 'Portanto, anulamos a Lei por meio da fé? Não seja (assim); ao contrário, confirmamos a Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28026, 17, 'Assim, que diremos ter encontrado Abraão, nosso antepassado segundo a carne?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28027, 17, 'Porque, se Abraão foi justificado a partir das obras, têm orgulho, mas não junto a Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28028, 17, 'pois que diz a Escritura? "Creu Abraão em Deus, e foi lançado em sua conta para justiça."');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28029, 17, 'Mas, ao que trabalha, o salário não é lançado em conta como uma dádiva, mas como dívida;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28030, 17, 'No entanto, ao que não trabalha, porém crê naquele que justifica o ímpio, a sua fé é lançada em conta (contabilizada) para justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28031, 17, 'Assim também Davi declara a bem-aventurança da pessoa (homem / ser humano) a quem Deus lança em conta (contabiliza) a justiça sem obras:');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28032, 17, '"Bem-aventurados aqueles cujas iniquidades são perdoadas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28033, 17, 'Bem-aventurado o homem a quem o Senhor jamais lance em conta (contabilize) o pecado."');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28034, 17, 'Assim, esta bem-aventurança (está) sobre a circuncisão, ou também sobre a incircuncisão? Visto que dizemos: A fé foi lançada em conta (contabilizada) a Abraão para justiça,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28035, 17, 'como, pois, foi lançada em conta (contabilizada)? Estando (ele) em circuncisão, ou em incircuncisão? Não em circuncisão, mas em incircuncisão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28036, 17, 'E recebeu o sinal de circuncisão, selo da justiça, (em razão) da fé que teve na incircuncisão, a fim de ser ele pai de todos os que creêm, durante a incircuncisão, para ser lançada em conta (contabilizada) a justiça a eles também;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28037, 17, 'e pai da circuncisão, - daqueles que não apenas são da circuncisão, mas que também andam nas pisadas da fé, de nosso pai Abraão, quando estava na incircuncisão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28038, 17, 'Pois, não foi por intermédio da Lei que (foi feita) à Abraão, ou à sua descendência, a promessa de ser o herdeiro do mundo, mas por intermédio da justiça da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28039, 17, 'Portanto, se os herdeiros (proveêm) da Lei, a fé foi esvaziada e a promessa anulada,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28040, 17, 'já que a Lei produz ira, mas onde não existe Lei, tampouco existe transgressão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28041, 17, 'Por isso, é a partir da fé, a fim de ser por graça, para ser firme a promessa a toda a descendência, não somente à (descendência) da Lei, mas também à (descendência) da fé de Abraão, o qual é pai de todos nós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28042, 17, 'Como está escrito: "Por pai de muitas nações te constituí", perante aquele no qual creu, o Deus que vivifica os mortos, e chama as coisas que não são, como se já fossem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28043, 17, 'Este (Abraão) que creu, (com superior) esperança, contra (toda) esperança, a fim de vir a ser pai de muitas nações, segundo o que foi dito: "Assim será a tua descendência",');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28044, 17, 'e, sem enfraquecer na fé, mesmo considerando o seu próprio corpo já mortificado, contando aproximadamente cem anos, bem como a esterilidade do ventre de Sara,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28045, 17, 'não duvidou, por ausência de fé, com relação à promessa de Deus, ao contrário, foi fortalecido pela fé, dando glória a Deus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28046, 17, 'convencido de que o que ele (Deus) prometeu, é também poderoso para fazer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28047, 17, 'Também por isso, lhe foi lançado em conta (contabilizado) para justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28048, 17, 'E não somente por causa dele está escrito que lhe foi lançado em conta (contabilizado),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28049, 17, 'mas também por nossa causa - a quem será lançado em conta (contabilizado) - nós que cremos naquele (Deus) que ressuscitou dentre os mortos a Jesus, nosso Senhor -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28050, 17, 'o qual foi entregue por causa das nossas transgressões, e ressuscitado por causa da nossa justificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28051, 17, 'Portanto, justificados pela fé, temos paz junto a Deus, através de Nosso Senhor Jesus Cristo,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28052, 17, 'por quem, também, temos acesso a esta <b>*caridade</b>*, na qual permanecemos; e nos gloriamos na esperança da glória de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28053, 17, 'E não somente, mas também nos gloriamos nas aflições, sabendo que a aflição produz resiliência (robustez).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28054, 17, 'E a resiliência (robustez) produz aprovação, e a aprovação (produz) esperança.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28055, 17, 'Ora, a esperança não decepciona, porque o amor de Deus foi derramado em nossos corações, mediante o Espírito Santo, que nos foi dado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28056, 17, 'Pois Cristo, quando ainda éramos fracos, na época oportuna, morreu pelos ímpios -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28057, 17, 'de modo raro - pois alguém morrerá por um justo, talvez por um bom alguém também ouse morrer;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28058, 17, 'no entanto, Deus nos mostra o seu próprio amor, pois, sendo ainda pecadores, Cristo morreu por nós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28059, 17, 'Assim, muito mais agora, estando justificados pelo seu sangue, seremos salvos da ira, por meio dele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28060, 17, 'Pois, se quando ainda inimigos, fomos reconciliados com Deus pela morte do seu Filho, uma vez já estando reconciliados, muito mais seremos salvos pela vida dele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28061, 17, 'E não somente isso, mas também nos gloriamos em Deus através de Nosso Senhor Jesus Cristo, por meio de quem recebemos agora a reconciliação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28062, 17, 'Portanto, assim como por um só homem entrou o pecado no mundo - e pelo pecado, a morte - assim também a morte passou a todos os homens, porque todos pecaram.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28063, 17, 'Assim, o pecado estava no mundo até (vir) a Lei, todavia, não existindo a Lei, o pecado não é levado em conta;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28064, 17, 'Entretanto, reinou a morte desde Adão até Moisés, mesmo sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual é um tipo daquele que havia de vir.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28065, 17, 'Todavia, a dádiva não é semelhante à transgressão - muito mais (é) a <b>caridade</b> (graça) de Deus - porque, se muitos morreram, pela transgressão de um, também a dádiva na (esfera) da <b>caridade</b> (graça) de um só homem - Jesus Cristo - foi abundante para muitos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28066, 17, 'O dom, entretanto, não é semelhante ao caso em que somente um  pecou; se por um lado, a partir de um, vem o juízo para condenação, por outro lado, a partir de muitas transgressões, vem a <b>caridade</b> (graça) para justificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28067, 17, 'Portanto, se, pela transgressão de apenas um, a morte reinou, através de um só; muito mais reinarão em vida - por meio de um só, a saber, Jesus Cristo - aqueles que receberam a abundância da <b>caridade</b> (graça) e a dádiva da justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28068, 17, 'Logo, assim como, por meio de uma transgressão, (veio o juízo) para condenação a todos os homens, assim também, por meio de um ato de justiça, veio a justificação de vida a todos os homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28069, 17, 'Do mesmo modo, assim como, por meio da desobediência de um só homem, foram constituídos os inúmeros pecadores, assim também, por meio da obediência de um só, serão constituídos os inúmeros justos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28070, 17, 'Agregou-se a isso, porém, a Lei, para que a transgressão se tornasse plena; todavia, onde abundou o pecado, superabundou a <b>caridade</b> (graça),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28071, 17, 'a fim de que, assim como reinou o pecado na morte, assim também reinasse a <b>caridade</b> (graça), através da justiça, para a vida eterna, por meio do Nosso Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28072, 17, 'Portanto, que diremos? Continuemos no pecado para que <b>caridade</b> (graça) se torne plena?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28073, 17, 'De modo nenhum! Nós, os que morremos para o pecado, como ainda viveremos nele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28074, 17, 'Ou ignorais que todos nós que fomos batizados em Cristo Jesus fomos batizados na sua morte?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28075, 17, 'Desse modo, através do batismo na morte, fomos sepultados com ele, a fim de que, do mesmo modo que Cristo foi ressuscitado dentre os mortos pela glória do Pai, assim também andemos nós em novidade de vida.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28076, 17, 'Porque, se nos tornamos unidos a ele na semelhança da sua morte, muito mais seremos na ressurreição.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28077, 17, 'Sabendo isto: que nosso homem velho foi crucificado com ele, a fim de que o corpo do pecado fosse destruído, de modo a não mais servirmos ao pecado;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28078, 17, 'porquanto quem morreu está justificado do pecado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28079, 17, 'E, se já morremos com Cristo, cremos que também viveremos com ele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28080, 17, 'Sabendo que Cristo, tendo sido ressuscitado dentre os mortos, não morre mais; a morte não mais o domina.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28081, 17, 'Pois, aquele que morreu, uma vez por todas morreu para o pecado, todavia, aquele que vive, para Deus vive.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28082, 17, 'Do mesmo modo, considerai-vos a vós mesmos como que estando, de um lado, mortos para o pecado, de outro lado, vivos para Deus, em Cristo Jesus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28083, 17, 'Assim, não reine o pecado em vosso corpo mortal, para obedecerdes às paixões dele,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28084, 17, 'nem apresenteis os vossos membros ao pecado, como instrumentos de injustiça, mas apresentai a vós mesmos a Deus, como os que vivem dentre os mortos, e (apresentai) a Deus os vossos membros como instrumentos de justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28085, 17, 'Assim, o pecado não vos dominará; não estais sob a Lei, mas sob a <b>caridade</b> (graça).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28086, 17, 'Portanto, que (diremos)? Pecaremos porque não estamos sob a Lei, mas sob a <b>caridade</b> (graça)? De modo nenhum\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28087, 17, 'Não sabeis que, daquele a quem vos apresenteis como escravos para obediência, desse mesmo - a quem obedeceis - sois escravos, tanto do pecado para a morte, quanto da obediência para a justiça?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28088, 17, 'Mas, graças a Deus que, mesmo tendo sido escravos do pecado, obedecestes de coração ao padrão (tipo) de ensino “ao qual fostes entregues” (que vos foi transmitido).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28089, 17, 'E, após terem sido libertados do pecado, fostes escravizados à justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28090, 17, 'Falo em termos humanos por conta “da fraqueza de vossa carne” (de vossa fragilidade), pois, assim como apresentastes os vossos membros, como escravos, à impureza e à iniquidade, para a iniquidade, do mesmo modo, apresentai agora os vossos membros, como escravos, à justiça, para santificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28091, 17, 'Porque, quando fostes escravos do pecado, estivestes livres com relação à justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28092, 17, 'Naquele tempo, que fruto tivestes? Somente as coisas de que, agora, vos envergonhais; porquanto a finalidade delas é morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28093, 17, 'Agora, porém, libertados do pecado, mas escravizados à Deus, tendes o vosso fruto para a santificação, cuja finalidade é vida eterna.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28094, 17, 'Pois, o salário do pecado é morte, mas a <b>caridade</b> (graça) de Deus é a vida eterna em Cristo Jesus, nosso Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28095, 17, 'Ou ignorais, irmãos - pois falo ao que conhecem a Lei - que a Lei tem domínio sobre o homem pelo tempo em que ele viver?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28096, 17, 'Sendo assim, a mulher casada está ligada pela Lei ao marido, enquanto ele vive; todavia, se o marido vier a morrer, está livre da "Lei do marido" (Lei conjugal).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28097, 17, 'Desse modo, será “chamada" (considerada) adúltera, se tornar-se de outro homem, enquanto viver o marido; porém, se morrer o marido, está livre da Lei, e ela não será adúltera, ao se tonar de outro homem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28098, 17, 'Assim, meus irmãos, também vós morrestes relativamente à Lei, por meio do corpo de Cristo, para tornarem-se de outro, daquele que ressuscitou dentre os mortos, a fim de que frutifiquemos para Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28099, 17, 'Porque, quando estávamos na carne, as paixões dos pecados - as que (surgem) através da Lei - operavam em nossos membros, a fim de frutificarmos para a morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28100, 17, 'Agora, porém, libertos da Lei, estamos mortos para aquilo a que estávamos presos, de modo a servirmos em novidade de espírito, e não em caducidade da letra.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28101, 17, 'Portanto, que diremos? A Lei é pecado? De modo nenhum! Todavia, eu não conheceria o pecado a não ser através da Lei; assim também, eu não teria conhecido a cobiça se não dissesse a Lei: Não cobiçarás.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28102, 17, 'Mas o pecado, tomando ocasião através do mandamento, operou em mim toda cobiça, pois sem a Lei o pecado está morto.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28103, 17, 'Outrora, eu vivia sem Lei, mas o pecado reviveu o mandamento.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28104, 17, 'E, eu morri; mas revelou-se para mim que o mandamento que era para  a vida, tornou-se para morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28105, 17, 'O pecado, tomando ocasião através do mandamento, me enganou; e, por meio dele, me matou');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28106, 17, 'Assim, a Lei é santa, o mandamento é santo, justo e bom.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28107, 17, 'Porventura, o que (era) bom para mim se tornou morte? De modo nenhum! Pelo contrário, o pecado, para revelar-se como pecado, através daquilo que (era) bom para mim, operou a morte; a fim de que, por meio do mandamento, se tornasse excessivamente pecaminoso.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28108, 17, 'Assim, sabemos que a Lei é espiritual, mas eu sou carnal, vendido no pecado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28109, 17, 'Pois não conheço o que produzo; Aquilo que quero, isto não pratico, mas aquilo que odeio, isto faço.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28110, 17, 'No entanto, se aquilo que não quero, isto faço, concordo com a Lei que (é) boa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28111, 17, 'Agora, porém, já não sou eu que produzo isto, mas o pecado que habita em mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28112, 17, 'Desse modo, sei que o bem não habita em mim, isto é, em minha carne; pois querer o bem está ao meu alcance, mas não produzi-lo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28113, 17, 'Pois o que quero - o bem - não faço, mas o que não quero - o mal - isto pratico.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28114, 17, 'Se o que não quero, isto eu faço, já não sou eu que produzo isso, mas o pecado que habita em mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28115, 17, 'Então, descubro a Lei: ao querer fazer o bem, o mal está ao meu alcance.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28116, 17, 'Sendo assim, tenho prazer na Lei de Deus, segundo o homem interior;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28117, 17, 'No entanto, vejo outra Lei, em meus membros, guerreando contra a Lei da minha mente, e me subjugando à Lei do pecado, que está em meus membros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28118, 17, 'Miserável homem que sou! Quem me livrará do corpo desta morte?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28119, 17, 'Graças a Deus, por meio de Jesus Cristo, nosso Senhor. Porquanto, mesmo assim, se por um lado sirvo à Lei de Deus com a mente, por outro lado (sirvo) à Lei do pecado com a carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28120, 17, 'Nenhuma condenação, portanto, (existe) agora para os que (estão) em Cristo Jesus;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28121, 17, 'pois a Lei do Espírito da vida, em Cristo Jesus, te libertou da Lei do pecado e da morte.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28122, 17, 'Porquanto - coisa impossível à Lei, posto que enfraquecida pela carne - Deus, enviando o seu próprio Filho, em carne semelhante à do pecado e no âmbito do pecado, condenou o pecado na (própria) carne,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28123, 17, 'a fim de que o preceito da Lei se cumprisse em nós, que não “<b>andamos</b>" (vivemos) segundo a carne, mas segundo o Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28124, 17, 'Assim, os que estão conforme à carne têm em mente as coisas da carne, mas os que estão conforme ao Espírito (têm em mente) as coisas do Espírito.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28125, 17, 'Porque o conteúdo mental da carne é morte, mas o conteúdo mental do Espírito é vida e paz;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28126, 17, 'por isso o conteúdo mental da carne é inimizade contra Deus, pois não está sujeito à Lei de Deus, nem é capaz de estar.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28127, 17, 'Os que estão conforme à carne não são capazes de agradar a Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28128, 17, 'Mas vós não estais na carne, mas no Espírito, caso o Espírito de Deus habite em vós. Todavia, se alguém não possui o Espírito do Cristo, este (alguém) não é dele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28129, 17, 'Se, porém, Cristo (está) em vós, o corpo está morto por causa do pecado, por outro lado o Espírito é vida, por causa da justiça.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28130, 17, 'No entanto, se habita em vós o Espírito que ressuscitou Jesus dentre os mortos, esse (mesmo) que ressuscitou Cristo dentre os mortos vivificará também vossos corpos mortais, por meio do seu Espírito, que em vós habita.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28131, 17, 'Assim, pois, somos devedores, (mas) não à carne, para vivermos conforme à carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28132, 17, 'Porque, se viveis conforme à carne estais prestes a morrer, mas pelo Espírito vivereis, se fizerdes morrer as ações do corpo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28133, 17, 'Todos os que são guiados pelo Espírito de Deus são filhos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28134, 17, 'Porque não recebestes novamente espírito de escravidão, para temor; mas recebestes espírito de filiação, pelo qual clamamos: Abba! Pai\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28135, 17, 'O próprio Espírito testemunha com o nosso espírito que somos filhos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28136, 17, 'Não somente filhos, mas também herdeiros. Herdeiros de Deus por um lado, e co-herdeiros de Cristo por outro, a fim de que também sejamos glorificados com Ele, acaso tenhamos sofrido com Ele.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28137, 17, 'Sendo assim, considero que os sofrimentos do tempo presente não são dignos de (serem comparados) com a glória vindoura, a ser revelada para nós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28138, 17, 'Assim, a intensa expectativa da criação aguarda a revelação dos filhos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28139, 17, 'Pois a criação foi sujeitada à futilidade, não voluntariamente, mas por causa daquele que a sujeitou, na esperança');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28140, 17, 'de que a própria criação também será libertada, da escravidão da corrupção rumo à liberdade da glória dos filhos de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28141, 17, 'Porque sabemos que toda a criação, em todo o seu conjunto, geme e agoniza de parto, até o presente.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28142, 17, 'E não somente ela, mas também nós, que temos as primícias do Espírito; também nós gememos, dentro de nós mesmos, aguardando a filiação,  e o resgate "redentor" de nosso corpo');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28143, 17, 'Porque, na esperança fomos salvos. Todavia, esperança que se vê não é esperança; pois quem espera aquilo que está vendo?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28144, 17, 'Por outro lado, se esperamos aquilo que não estamos vendo, aguardamos com resiliência (robustez).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28145, 17, 'Também o Espírito, de modo semelhante, nos auxilia em nossa fraqueza; pois não sabemos, como é necessário (saber), o que devemos orar. No entanto, o próprio Espírito intercede com gemidos indescritíveis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28146, 17, 'E aquele que examina os corações sabe qual o o conteúdo mental do Espírito, porque ele intercede pelos Santos, em conformidade com Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28147, 17, 'Sabemos que, àqueles que amam a Deus, aos que são chamados segundo seu propósito, todas as coisas cooperam para o bem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28148, 17, 'Porquanto, àqueles que previamente conheceu, também os escolheu previamente (para terem) a mesma forma da imagem de seu Filho, para ser ele o primogênito entre muitos irmãos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28149, 17, 'E aos que previamente escolheu, a esses também chamou; e aos que chamou, a esses também justificou; e aos que justificou, a esses também glorificou.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28150, 17, 'Assim, diante destas coisas, que diremos? Se Deus é por nós, quem será contra nós?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28151, 17, 'Aquele que não poupou o seu próprio Filho, antes, o entregou por todos nós, porventura, não nos doará todas as coisas, junto com ele?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28152, 17, 'Quem trará acusações contra os eleitos de Deus? Deus é aquele que justifica.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28153, 17, 'Quem é aquele que condena? É Cristo, aquele que morreu, ou melhor, foi ressuscitado; o qual está à direita de Deus, o qual também intercede por nós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28154, 17, 'Quem nos separará do amor de Cristo? (Será) aflição, ou angústia , ou perseguição, ou fome, ou nudez, ou perigo, ou espada?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28155, 17, 'Conforme está escrito: “Por causa de ti somos mortos o dia todo, fomos considerados como ovelhas de matadouro”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28156, 17, 'Em todas estas coisas, porém, somos mais que vencedores, por meio daquele que nos amou.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28157, 17, 'Portanto, estou convencido de que nem morte, nem vida, nem anjos, nem autoridades, nem coisas presentes, nem coisas vindouras, nem poderes,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28158, 17, 'nem altura, nem profundidade, nem qualquer outra criatura poderá nos separar do amor de Deus, em Cristo Jesus, nosso Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28159, 17, 'Falo a verdade, em Cristo, não minto - co-testemunhando comigo a minha consciência, no Espírito Santo -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28160, 17, 'que há, em mim, uma grande tristeza e uma incessante dor no meu coração;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28161, 17, 'porque eu mesmo desejaria ser anátema, (apartado) de Cristo, em lugar dos meus irmãos, dos meus compatriotas segundo a carne -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28162, 17, 'que são os Israelitas - deles são a filiação e a glória, as alianças e a entrega da Lei, o culto e as promessas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28163, 17, 'deles são os patriarcas, dentre os quais, segundo a carne, (descende) o Cristo, o qual é sobre todos - bendito seja Deus para sempre, Amém\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28164, 17, 'Entretanto, não (é) que a palavra de Deus tenha falhado, pois nem todos os que (provem) de Israel são Israel;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28165, 17, 'nem porque são descendência de Abraão são todos filhos, porém “em Isaque será chamada a tua descendência”,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28166, 17, 'isto é, estes filhos de Deus não são os filhos da carne, mas são contados para (efeito de) descendência os filhos da promessa.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28167, 17, 'Sendo assim, esta (é) a palavra da promessa: “Por esta época virei; e Sara terá um filho.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28168, 17, 'E não somente (ela), mas também Rebeca que, a partir de um só leito, concebeu de Isaque, nosso pai.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28169, 17, 'E, quando ainda não haviam nascido (os gêmeos) - não tendo feito nem algo de bom, nem (algo) de mal, a fim de que a eleição permanecesse conforme o propósito de Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28170, 17, 'não por obras, mas por aquele que chama - foi dito a ela: ”O maior será servo do menor”,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28171, 17, 'como está escrito: “Amei Jacó, mas odiei Esaú”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28172, 17, 'Portanto, que diremos? Acaso há injustiça da parte de Deus? De modo nenhum\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28173, 17, 'Pois (ele) diz a Moisés: “Terei misericórdia de quem eu tiver misericórdia e me compadecerei de quem eu me compadecer”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28174, 17, 'Desse modo, não (depende) do que quer, nem do que corre, mas daquele que tem misericórdia - Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28175, 17, 'Porquanto a Escritura diz a Faraó: “Para isto mesmo te levantei, para mostrar em ti o meu poder, e para que o meu nome seja anunciado em toda a Terra”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28176, 17, 'Sendo assim, tem misericórdia de quem ele quer, mas endurece quem ele quer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28177, 17, 'Dirás, porém, a mim: Por que, então, (ele) ainda culpa alguém? Pois, quem resistiu à sua vontade?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28178, 17, 'Afinal, quem és tu - Ó homem - que contestas a Deus? Acaso, aquilo que foi plasmado dirá àquele que o plasmou: Por que me fizeste assim?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28179, 17, 'Ou não tem o oleiro autoridade sobre a argila, para fazer da mesma massa um vaso para honra e outro para desonra?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28180, 17, 'Se Deus, querendo demonstrar a sua ira e tornar conhecido o seu poder, suportou com muita longanimidade vasos de ira preparados para destruição,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28181, 17, 'a fim de que fosse conhecida a riqueza da sua glória para com os vasos de misericórdia, que foram previamente preparados para glória.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28182, 17, 'E também nos chamou, não somente dentre os Judeus, mas também dentre os Gentios,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28183, 17, 'conforme (ele)diz em Oséias: “Chamarei povo meu ao que não (é) meu povo; e amada, à que não (é) amada;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28184, 17, 'e acontecerá que no lugar onde lhes foi dito: Vós não sois meu povo; lá serão chamados filhos do Deus vivo”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28185, 17, 'Isaías, por sua vez, clama a respeito de Israel: “Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28186, 17, 'Porque o Senhor executará uma palavra que levará a termo e abreviará (o tempo) sobre a Terra”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28187, 17, 'Conforme predisse Isaías: “Se o Senhor dos Exércitos não nos tivesse deixado descendência, teríamos nos tornado como Sodoma, e teríamos nos assemelhado à Gomorra”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28188, 17, 'Portanto, que diremos? Que os Gentios, mesmo não buscando justiça, receberam justiça, porém, justiça da fé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28189, 17, 'Por outro lado, Israel, buscando uma Lei de justiça, não atingiu essa Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28190, 17, 'Por que? Porque não (decorreu) da fé, mas (decorreu) como que das obras. Tropeçaram na pedra de tropeço,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28191, 17, 'como está escrito: “Eis que coloco em Sião um pedra de tropeço, e rocha de escândalo. E aquele que nela crê não será envergonhado”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28192, 17, 'Irmãos, o desejo do meu coração e a (minha) súplica, junto a Deus, por eles, é para salvação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28193, 17, 'Porque testemunho por eles que possuem zelo de Deus, porém não com conhecimento.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28194, 17, 'Porquanto, desconhecendo a justiça de Deus, e procurando estabelecer a sua própria, não se sujeitaram à justiça de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28195, 17, 'Pois a finalidade da Lei é Cristo, para justiça de todo aquele que crê.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28196, 17, 'Assim, Moisés escreve (sobre) a justiça (que decorre) da Lei: Que o homem que pratica estas coisas viverá por elas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28197, 17, 'Mas, sobre a justiça (que decorre) da fé, assim diz: “Não digas em teu coração: Quem subirá ao céu?” Isto é, para fazer Cristo descer;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28198, 17, 'Ou, “Quem descerá ao abismo?” Isto é, para fazer Cristo se levantar dentre os mortos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28199, 17, 'Porém, que diz? “Perto de ti está a palavra, na tua boca, e no teu coração”. Isto é, a palavra da fé, que proclamamos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28200, 17, 'Porque se professares, com a tua boca, o Senhor Jesus, e crerdes, em teu coração, que Deus o ressuscitou dentre os mortos, serás salvo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28201, 17, 'Pois com o coração se crê para justiça, e com a boca se professa para salvação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28202, 17, 'Porquanto, diz a Escritura: “Todo aquele que nele crê não será envergonhado”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28203, 17, 'Portanto, não há distinção entre Judeu e Grego, pois o Senhor (é) o mesmo para todos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28204, 17, 'Assim, todo aquele que invocar o nome do Senhor será salvo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28205, 17, 'Como, porém, invocarão aquele em quem (eles) não creram? E como crerão naquele do qual não ouviram? E como ouvirão, se não há quem proclame?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28206, 17, 'E como proclamarão, se não foram enviados? Conforme está escrito: “Como são formosos os pés dos que evangelizam as coisas boas”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28207, 17, 'Mas nem todos obedeceram ao evangelho, pois diz Isaías: “Senhor, quem creu em nossa mensagem?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28208, 17, 'Assim, a fé (decorre) da mensagem, e a mensagem (surge) através da palavra de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28209, 17, 'Digo, porém: Porventura, não ouviram? Certamente. “Para toda a terra saiu a declaração deles, e para os confins do mundo as palavras deles”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28210, 17, 'No entanto, digo: Porventura, Israel não soube? Moisés diz: “Eu provocarei ciúmes em vós com quem não é (o) povo, com um povo insensato vos irritarei”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28211, 17, 'Isaías ousa, e diz: “Fui encontrado pelos que não me procuram, me fiz manifesto aos que não perguntam por mim”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28212, 17, 'Para Israel, porém, diz: “Todo o dia estendi as minhas mãos a um povo desobediente e opositor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28213, 17, 'Digo, pois: Porventura, Deus terá rejeitado o seu povo? De modo nenhum! Pois, eu também sou Israelita, da descendência de Abraão, da Tribo de Benjamim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28214, 17, 'Deus não rejeitou o seu povo, a quem conheceu previamente. Ou não sabeis o que diz a Escritura a respeito de Elias, como (ele) implora a Deus, contra Israel?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28215, 17, '“Senhor, mataram os teus profetas, demoliram os teus altares; eu fui deixado sozinho, e procuram (tirar) a minha vida”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28216, 17, 'O que lhe disse, porém, a revelação divina? “Reservei para mim mesmo sete mil homens, os quais não dobraram o joelho a Baal”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28217, 17, 'Assim, pois, também na presente época, surgiu um remanescente, segundo a eleição da <b>caridade</b> (graça).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28218, 17, 'E, se (é) pela <b>caridade</b> (graça), já não (é) pelas obras; do contrário, a <b>caridade</b> (graça) não mais se torna <b>caridade</b> (graça).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28219, 17, 'Que (diremos), pois? O que Israel almeja, isso não alcança; mas a eleição alcança (Israel). Os demais, porém, foram endurecidos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28220, 17, 'conforme está escrito: “Deus lhes deu espírito de torpor, olhos (para) não ver, e ouvidos (para) não ouvir, até o dia de hoje”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28221, 17, 'E Davi diz: “Torne-se a mesa deles em armadilha, em laço, em escândalo;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28222, 17, 'escureçam-se os olhos deles, (para) não ver, e dobra o dorso deles por todo (sempre)”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28223, 17, 'No entanto, digo: Porventura, tropeçaram para que caíssem? De modo nenhum! Mas no tropeço deles (veio) a salvação aos gentios, para provocar ciúmes neles (os Judeus).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28224, 17, 'Todavia, se o tropeço deles (é) riqueza do mundo, e o fracasso deles (é) riqueza dos Gentios, muito mais (será) a plenitude deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28225, 17, 'Mas digo a vós, aos Gentios! Visto, pois, que eu sou apóstolo dos Gentios, glorifico o meu ministério,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28226, 17, '(para ver) se de algum modo provoco ciúmes aos de minha carne (Judeus), e salve alguns dentre eles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28227, 17, 'Pois, se a rejeição deles (é) reconciliação do mundo, que (será) da aceitação, senão vida dentre os mortos?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28228, 17, 'E, se as primícias (são) santas, também (é) a mistura (da massa de pão); e se a raiz (é) santa, também (são) os ramos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28229, 17, 'E, se alguns dos ramos foram quebrados, mas tu - sendo oliveira brava - foste enxertado entre eles, e te tornaste co-participante da raiz e da seiva da oliveira,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28230, 17, 'não te enchas de soberba contra os ramos; porém, se te encheres de soberba, (saibas) que não (és) tu quem sustentas a raiz, mas (é) a raiz (quem sustenta) a ti.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28231, 17, 'Dirás, então: (Os) ramos foram quebrados a fim de que eu fosse enxertado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28232, 17, 'Bem! Pela incredulidade foram quebrados, tu, porém, estás firme pela fé. Não penses coisas elevadas (não tenhas arrogância), mas teme.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28233, 17, 'Porquanto, se Deus não poupou os ramos (que são) conforme a natureza, talvez nem a ti poupará.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28234, 17, 'Vê, portanto, a bondade e a severidade (de Deus); sobre os que caíram, severidade, mas sobre ti bondade de Deus, se permaneceres na bondade; do contrário, também tu serás cortado');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28235, 17, 'E, se aqueles (os Judeus) não permanecerem na incredulidade, serão enxertados, pois poderoso é Deus para novamente tornar a enxertá-los.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28236, 17, 'Portanto, se foste cortado da que , conforme a natureza, (era) oliveira brava, e foste enxertado, contra a natureza, na oliveira cultivada; muito mais estes - os que, conforme a natureza, serão enxertados - na própria oliveira.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28237, 17, 'Porque não quero, irmãos, que ignoreis este mistério, para que não vos tenhais, a vós mesmos, (na conta de) sábios: que sobreveio o endurecimento sobre Israel, em parte, até que a plenitude dos Gentios entre (seja alcançada).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28238, 17, 'E, assim, todo o Israel será salvo, como está escrito: “Virá de Sião o libertador, irá transmutar (teshuva) as impiedade de Jacó;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28239, 17, 'Esta é a minha aliança com eles, quando eu remover os seus pecados”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28240, 17, 'Quanto ao Evangelho, (são) inimigos, por vossa causa, mas quanto à eleição (são) amados, por causa dos patriarcas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28241, 17, 'Porque as dádivas e a convocação de Deus (são) irrevogáveis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28242, 17, 'Pois, como outrora vós desobedecestes a Deus, mas agora obtivestes misericórdia, por conta da desobediência deles (os Judeus),');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28243, 17, 'assim também eles, agora, desobedeceram, por conta da vossa misericórdia, a fim de que eles também recebam misericórdia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28244, 17, 'Desse modo, Deus confinou a todos na desobediência, a fim de que todos (alcancem) misericórdia.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28245, 17, 'Ó profundidade de riqueza, sabedoria e conhecimento de Deus; como (são) insondáveis os seus juízos, e inescrutáveis os seus caminhos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28246, 17, '“Pois quem conhece a mente do Senhor? Ou quem se torna seu conselheiro?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28247, 17, 'Ou quem primeiro deu a ele, para que lhe venha a ser restituído?');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28248, 17, 'Porque dele, por meio dele e para ele (são) todas as coisas. Glória para sempre a ele. Amém\!');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28249, 17, 'Portanto, vos apelo, Irmãos, pelas misericórdias de Deus, a apresentardes vossos corpos (por) sacrifício vivo, santo e agradável a Deus, (que representa) o vosso culto genuíno.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28250, 17, 'Não vos moldeis (em conformidade) à esta era, mas transformai-vos pela renovação da mente, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28251, 17, 'Porque, pela <b>caridade</b> (graça) que me foi doada, digo, a todos os que estão entre vós, para não tenham de si mesmo um conceito mais elevado do que convém ter, mas que tenham um conceito moderado, conforme a medida da fé que Deus repartiu a cada um.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28252, 17, 'Porquanto, assim como temos muitos membros em um só corpo, mas nem todos os membros têm a mesma função,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28253, 17, 'assim também, (conquanto) muitos, somos um só corpo em Cristo, e membros, uns em relação aos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28254, 17, 'tendo, porém, diferentes dádivas, conforme a <b>caridade</b> (graça) que nos foi doada: se profecia, (exerça) segundo a proporção da fé;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28255, 17, 'se (é) ministério, (exerça) no ministério; se (é) o que ensina, (exerça) no ensino;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28256, 17, 'se (é) o que exorta, (exerça) na exortação; se (é) o que compartilha, (exerça) com generosidade; se (é) o que lidera, (exerça) com zelo; se (é) o que se compadece, (exerça) com alegria.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28257, 17, '(Que) o amor (seja) sem hipocrisia, detestando o mal, e unindo-se ao bem;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28258, 17, 'com amor fraternal, sendo cordiais uns com os outros, considerando os outros como mais dignos de honra.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28259, 17, '(Agindo) com diligência, sem indolência, mantendo o fervor no espírito, servindo ao Senhor,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28260, 17, 'regozijando na esperança, suportando na aflição, sendo persistentes na oração;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28261, 17, 'compartilhando as necessidades dos santos, e perseguindo a hospitalidade.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28262, 17, 'Abençoai os que vos perseguem; abençoai, não amaldiçoeis.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28263, 17, 'Alegrai-vos com os que se alegram, chorai com os que choram;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28264, 17, 'considerando-vos uns aos outros; tendo em mente não as coisas elevadas, mas dedicando-se às humildes. Não sejais sábios aos próprios olhos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28265, 17, 'A ninguém retribuindo o mal com o mal, e atentando para as coisas boas, perante todos os homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28266, 17, 'Se possível, no (que depender) de vós, vivendo em paz com todos os homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28267, 17, 'Não vingueis a vós mesmos, amados; mas dai lugar à ira (de Deus), pois está escrito: “A vingança (é) minha, eu retribuirei”, diz o Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28268, 17, 'Ao contrário, “se o teu inimigo tiver fome, alimenta-o; se tiver sede, dá-lhe de beber, pois fazendo isso, amontoarás brasas de fogo sobre a cabeça dele”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28269, 17, 'Não sejais vencido pelo mal, mas vence o mal com o bem.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28270, 17, 'Toda <b>alma</b> (pessoa) está sujeita às autoridades que exercem domínio, pois não há autoridade que não (se subordine) à Deus, e as que existem foram colocadas em ordem por Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28271, 17, 'Assim, o que se opõe à autoridade, resiste à ordenança de Deus; os que resistem, porém, receberão condenação sobre si mesmos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28272, 17, 'Porquanto, os que governam não representam um temor para a boa obra, porém para a má. Queres não temer a autoridade? Faze o bem, e terás a aprovação dela.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28273, 17, 'Pois, (a autoridade) é ministro de Deus para o teu (próprio) bem. Entretanto, se fizeres o mal, teme; porque não é em vão que (ela) traz a espada. Sendo assim, (a autoridade) é ministro de Deus, aquela que pune, para ira, aos que praticam o mal.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28274, 17, 'Por isso, a necessidade de estar sujeito (à autoridade), não somente por causa da ira, mas também por causa  da consciência.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28275, 17, 'Por isso também pagais tributo, porquanto (eles) são servos de Deus, estando a serviço disso.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28276, 17, 'Pagai, a todos, as dívidas: a quem o tributo, o tributo; a quem imposto, o imposto; a quem o temor, o temor; e a quem a honra, a honra.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28277, 17, 'Nada devam a ninguém, exceto o amardes uns aos outros. Porquanto, cumpre a Lei aquele que ama ao outro.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28278, 17, 'Porque, o “Não adulterarás”, “Não matarás“, “Não furtarás“, “Não cobiçaras“ - e se existe algum outro mandamento - nesta palavra se resume: “Amarás ao teu próximo como a ti mesmo”');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28279, 17, 'O amor ao próximo não pratica o mal, pois o amor é cumprimento da Lei.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28280, 17, 'E sabendo isto: que já é hora - o tempo oportuno - para serdes despertados do sono, pois a nossa salvação está mais perto de nós do que na ocasião em que passamos a crer.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28281, 17, 'A noite avançou, o dia se aproxima. Portanto, afastemo-nos das obras da escuridão, e vistamos as armas da luz.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28282, 17, 'Andemos de modo apropriado, como em (pleno) dia, não em folias e bebedeiras, imoralidade sexual e devassidão, discórdia e inveja,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28283, 17, 'mas vesti-vos do Senhor Jesus Cristo, e não façais provisão para os desejos da carne.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28284, 17, 'Acolhei ao que está debilitado na fé, não, porém, para disputa de opiniões.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28285, 17, 'Um crê (poder) comer todas as coisas, mas o que está débil come verduras.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28286, 17, 'Aquele que come não desdenhe aquele que não come; e aquele que não come não julgue aquele que come, pois Deus o acolheu.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28287, 17, 'Quem és tu que julgas o servo (doméstico) alheio? “Para o seu próprio Senhor se mantém de pé ou cai” (exp. idiomática). O Senhor, porém, é poderoso para mantê-lo de pé.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28288, 17, 'Desse modo, enquanto um julga ser um dia melhor que outro dia, outro julga serem iguais todos os dias; (E) cada um está plenamente convencido “em sua própria mente” (exp. idiomática: aos seus próprios olhos).');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28289, 17, 'Aquele que atenta para o dia, atenta para o Senhor; e aquele que come, para o Senhor come, sendo, pois, grato a Deus; e aquele que não come, para o Senhor não come, sendo grato a Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28290, 17, 'Portanto, nenhum de nós vive para si mesmo, e ninguém morre para si mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28291, 17, 'Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. Assim, se tanto vivemos quanto morremos (para Ele), somos do Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28292, 17, 'Portanto, para isso Cristo morreu e reviveu, a fim de que (ele) seja senhor tanto de mortos quanto de vivos');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28293, 17, 'Tu, porém, por que julgas teu irmão? E tu, por que desdenhas o teu irmão? Pois todos compareceremos diante do Tribunal de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28294, 17, 'Porque está escrito: “Eu vivo (para garantir), diz o Senhor, que todo joelho se dobrará para mim, e toda língua confessará (publicamente) a Deus”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28295, 17, 'Assim, portanto, cada um de nós prestará contas a Deus, a respeito de si mesmo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28296, 17, 'Desse modo, não nos julguemos mais uns aos outros. Ao contrário, decide antes isto: não colocar tropeço ou (pedra de) escândalo ao irmão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28297, 17, 'Sei, e estou persuadido no Senhor Jesus, que nada (é) impuro por si mesmo, exceto ao que considera ser impuro algo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28298, 17, 'Portanto, se por causa da comida o teu irmão se angustia, já não andas segundo o amor. Não destruas, com a tua comida, aquele por quem Cristo morreu.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28299, 17, 'Assim, não seja o vosso bem blasfemado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28300, 17, 'Porque o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28301, 17, 'Aquele que serve a Cristo deste modo é agradável a Deus, e aprovado pelos homens.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28302, 17, 'Assim, pois, persigamos as coisas da paz, as coisas (relativas) à edificação uns dos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28303, 17, 'Não destruas, por causa da comida, a obra de Deus. Todas as coisas são puras, por outro lado, (é) um mau comer com escândalo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28304, 17, '(É) bom não comer carne, nem beber vinho, nem (fazer) algo em que ofenda teu irmão.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28305, 17, 'A fé que tens, tem-na para ti mesmo perante Deus. Bem-aventurado aquele que não condena a si mesmo naquilo que aprova');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28306, 17, 'Todavia, aquele que disputa, se comer, está condenado, porque não (provêm) da fé; Tudo que não (provêm) da fé é pecado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28307, 17, 'E nós, os fortes, devemos suportar as debilidades dos fracos; não , porém, agradar a nós mesmos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28308, 17, 'Cada um de nós agrade ao próximo para o bem, em favor da edificação.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28309, 17, 'Porque o Cristo também não agradou a si mesmo; antes, como está escrito: “Os insultos dos que te insultam caíram sobre mim”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28310, 17, 'Porquanto, as coisas que previamente foram escritas, para o nosso ensino foram escritas, a fim de que, pela resiliência (robustez) e pela consolação (provenientes) das Escrituras, tenhamos esperança.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28311, 17, 'O Deus da resiliência (robustez) e da consolação vos dê o mesmo pensar, uns em relação aos outros, segundo Cristo Jesus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28312, 17, 'a fim de que, com uma só boca, unanimemente, glorifiqueis ao Deus e Pai de Nosso Senhor Jesus Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28313, 17, 'Por isso, acolhei-vos uns aos outros, como também Cristo vos acolheu, para a glória de Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28314, 17, 'Digo, pois, que Cristo se tornou ministro da circuncisão, por causa da verdade de Deus, para confirmar as promessas (feitas) aos patriarcas;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28315, 17, 'e, por causa da misericórdia, para os Gentios glorificarem a Deus, como está escrito: “Por isso te confessarei entre os Gentios, e cantarei louvores ao teu nome”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28316, 17, 'E outra vez diz: “Rejubilai, Gentios, com o povo dele (de Deus)”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28317, 17, 'E outra vez: “Louvai, todos os Gentios, ao Senhor, e louvem a ele todos os povos”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28318, 17, 'Também, outra vez, diz Isaías: “Haverá a raiz de Jessé, aquele que se levanta para governar os Gentios; nele, os Gentios terão esperança”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28319, 17, 'O Deus da esperança vos torne plenos de toda alegria e paz em crer, para que vos transbordeis de esperança no poder do Espírito Santo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28320, 17, 'E, eu mesmo, também estou convencido, meus irmãos, a respeito de vós, de que estais cheios de bondade, plenos de todo conhecimento, como também capazes de admoestar-vos uns aos outros.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28321, 17, 'Entretanto, audaciosamente, vos escrevi, em parte, como que vos relembrando, por causa da <b>caridade</b> (graça) que me foi doada por Deus  -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28322, 17, 'a fim de ser eu ministro de Cristo Jesus para os Gentios - servindo como sacerdote ao evangelho de Deus; para que a oferenda (cultual) dos Gentios se torne aceitável, e santificada no Espírito Santo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28323, 17, 'Porquanto, tenho orgulho, em Cristo Jesus, nas coisas concernentes a Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28324, 17, 'Portanto, não ousarei dizer algo, exceto das coisas que Cristo realizou por meu intermédio, para (estimular) obediência, por palavras e por obras, dos Gentios;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28325, 17, 'pelo poder de sinais e prodígios, pelo poder do Espírito de Deus, a ponto de eu, desde Jerusalém até ao redor do Ilírico, ter anunciado plenamente o evangelho de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28326, 17, 'E, ambicionando, assim, evangelizar - não onde já se conhece o nome de Cristo - a fim de que (eu) não edifique sobre alicerce alheio,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28327, 17, 'como está escrito: “Àqueles a quem não foi anunciado a respeito dele, (estes) verão, e os que não têm ouvido, (estes) entenderão”.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28328, 17, 'Por esta razão, também, fui impedido, muitas vezes, de ir até vós;');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28329, 17, 'Agora, porém, já não tendo lugar nestas regiões (para meu trabalho); desejando, há muitos anos, e necessitando ir até vós -');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28330, 17, 'quando eu for para a Espanha - espero vos ver, pois, quando (eu) estiver de passagem, e for por vós encaminhado para lá (Espanha), depois de haver primeiro desfrutado um pouco de vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28331, 17, 'Agora, porém, vou para Jerusalém servir aos Santos.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28332, 17, 'Porque Macedônia e Acaia entenderam ser melhor fazer certa contribuição aos pobres dos Santos (que estão) em Jerusalém.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28333, 17, 'Entenderam ser melhor, porque, também são devedores deles; pois, se nas coisas espirituais deles os Gentios entraram em comunhão, devem também servi-los nas coisas materiais.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28334, 17, 'Tendo, pois, concluído isto e havendo-lhes consignado este fruto,  partirei, passando por vós, para a Espanha.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28335, 17, 'Sei que, indo até vós, irei na plenitude da bênção de Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28336, 17, 'Rogo-vos, irmãos, por nosso Senhor Jesus Cristo, e pelo amor do Espírito, que luteis comigo, nas orações por mim junto a Deus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28337, 17, 'a fim de que (eu) seja resgatado dos desobedientes na Judéia, e que (este) meu serviço em favor de Jerusalém se torne aceitável aos Santos');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28338, 17, 'para que, quando chegar até vós, pela vontade de Deus, com alegria, desfrute um descanso convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28339, 17, 'O Deus da paz (esteja) com todos vós. Amém.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28340, 17, 'Recomendo-vos a nossa irmã Fede, que é servidora da igreja em Cencréia,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28341, 17, 'para que a recebais no Senhor, do modo apropriado aos Santos, e a ajudeis nas coisas que ela de vós necessitar, pois se tornou protetora de muitos, de mim mesmo também.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28342, 17, 'Saudai Prisca e Áquila, os meus cooperadores em Cristo Jesus,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28343, 17, 'os quais arriscaram seu próprio pescoço pela minha vida; a quem não somente eu agradeço, mas também todas as igrejas dos Gentios.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28344, 17, 'Saudai, também, a igreja (que se reúne) na casa deles. Saudai meu amado Epêneto, primícias da Ásia para Cristo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28345, 17, 'Saudai Maria, que muito arduamente trabalhou por vós.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28346, 17, 'Saudai Andrônico e Junias, meus compatriotas e meus co-prisioneiros, que são notáveis entre os apóstolos, os quais estavam em Cristo antes de mim.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28347, 17, 'Saudai Amplíato, meu amado no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28348, 17, 'Saudai Urbano, nosso cooperador em Cristo, e Estáquis, meu amado.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28349, 17, 'Saudai Apeles, o aprovado em Cristo. Saudai os (da casa) de Aristóbulo.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28350, 17, 'Saudai Herodião, meu compatriota. Saudai os (da casa) de Narciso, que estão no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28351, 17, 'Saudai Trifena e Trifona, que trabalham arduamente no Senhor. Saudai Perside, a amada, que muito arduamente trabalhou no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28352, 17, 'Saudai Rufo, o eleito do Senhor, e igualmente a sua mãe, minha (mãe) também.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28353, 17, 'Saudai Asincrito, Flegonte, Hermes, Pátrobas, Hermas, e os irmãos (que estão) junto deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28354, 17, 'Saudai Filólogo e Julia, Nereu e sua irmã, Olímpias e todos os Santos (que estão) junto deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28355, 17, 'Saudai-vos uns aos outros com ósculo santo. Todas as igrejas de Cristo vos saúdam.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28356, 17, 'Rogo-vos, irmãos, observem aqueles que provocam as divisões e os escândalos, contrários à doutrina que aprendestes. Afastai-vos deles.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28357, 17, 'Porquanto, esses tais não servem ao Nosso Senhor, Cristo, mas (servem) ao seu próprio ventre, e por meio de formosas palavras e lisonjas enganam os corações dos simples.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28358, 17, 'Pois a vossa obediência chegou (ao conhecimento) de todos. Por isso, me alegro por vós. Quero que sejais sábios para o bem, porém, puros para o mal.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28359, 17, 'O Deus da paz esmagará Satanás, sob os vossos pés, em breve. A <b>caridade</b> (graça) de Nosso Senhor Jesus (esteja) convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28360, 17, 'Saúda-vos Timóteo, o meu cooperador, também Lúcio, Jasão e Sosípatro, os meus compatriotas.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28361, 17, 'Eu, Tércio, aquele que redigiu a epístola, vos saúdo no Senhor.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28362, 17, 'Saúda-vos Gaio, aquele que me hospeda, e também toda a igreja. Saúda-vos Erasto, o administrador da cidade, e o irmão Quarto.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28363, 17, '(A <b>caridade</b> (graça) de Nosso Senhor Jesus Cristo (esteja) convosco.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28364, 17, 'E (glória) àquele que é capaz de vos confirmar, segundo o meu evangelho e (segundo) a pregação de Jesus Cristo, segundo a revelação do mistério, guardado em silêncio nos tempos eternos,');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28365, 17, 'manifestado, porém, agora; e dado a conhecer a todas as nações para obediência da fé, através dos escritos proféticos, segundo o mandamento do Eterno Deus.');
INSERT INTO verse_text (verse_id, version_id, text) VALUES (28366, 17, 'Deus, o único sábio, por meio de Jesus Cristo, a quem (seja dada) glória para sempre. Amém.');